### EDA on Kaggle

- https://www.kaggle.com/vanguarde/h-m-eda-first-look
- https://www.kaggle.com/gpreda/h-m-eda-and-prediction
- https://www.kaggle.com/remekkinas/h-m-eda-first-look-into-data
- https://www.kaggle.com/vickeytomer/h-m-eda-exploration
- https://www.kaggle.com/negoto/best-selling-items-catalog-like-eda-of-articles

In [1]:
import pandas as pd

In [3]:
#read transaction.csv
transaction_raw = pd.read_csv("../data/transactions_train.csv") 

In [4]:
transaction_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31788324 entries, 0 to 31788323
Data columns (total 5 columns):
 #   Column            Dtype  
---  ------            -----  
 0   t_dat             object 
 1   customer_id       object 
 2   article_id        int64  
 3   price             float64
 4   sales_channel_id  int64  
dtypes: float64(1), int64(2), object(2)
memory usage: 1.2+ GB


In [5]:
transaction_raw.head()

t_dat                                        customer_id  article_id  \
0  2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   663713001   
1  2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   541518023   
2  2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   505221004   
3  2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   685687003   
4  2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   685687004   

      price  sales_channel_id  
0  0.050831                 2  
1  0.030492                 2  
2  0.015237                 2  
3  0.016932                 2  
4  0.016932                 2

In [6]:
#check start date and last date
print("Start date:", transaction_raw.t_dat.min())
print("Last date:", transaction_raw.t_dat.max())

Start date: 2018-09-20
Last date: 2020-09-22


In [7]:
#get data between 2019-5-1 and 2019-8-1
transaction_raw.t_dat = pd.to_datetime(transaction_raw.t_dat)
mask = (transaction_raw.t_dat >= '2019-05-01') & (transaction_raw.t_dat <= '2019-08-01')
transaction_raw_2019 = transaction_raw.loc[mask].reset_index(drop=True)

In [8]:
transaction_raw_2019

t_dat                                        customer_id  \
0       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
1       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
2       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
3       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
4       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
...            ...                                                ...   
5326381 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
5326382 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
5326383 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
5326384 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
5326385 2019-08-01  fff887d056fff68679d6e2491588ee4e83e57bf077ca7a...   

         article_id     price  sales_channel_id  
0         524061003  0.050831                 2  
1         735404001  0.050831                 2  
2         700370004  0.016932                 2  
3         618800001  0.033881                 2  
4         731407001  0.016932                 2  
...             ...       ...               ...  
5326381   719209001  0.016932                 2  
5326382   720426001  0.025407                 2  
5326383   713199001  0.033881                 2  
5326384   739590002  0.016932                 2  
5326385   713774006  0.022017                 1  

[5326386 rows x 5 columns]

In [9]:
#the number of customers and the number of items they purchase
print("Number of customers:",transaction_raw_2019.customer_id.nunique())
print("Total number of purchased items:", len(transaction_raw_2019))
#transaction_raw_2019.customer_id.value_counts()

Number of customers: 562225
Total number of purchased items: 5326386


In [10]:
#number of uniuqe items purchased in 2019 summer
print("Number of unique items:", transaction_raw_2019.article_id.nunique())
#transaction_raw_2019.article_id.value_counts()

Number of unique items: 44117


In [11]:
#Top-20 selling article IDs
freq_cnt = transaction_raw_2019.article_id.value_counts()
top20_article_id = list(freq_cnt.index[0:20])
top20_article_id 

[759871002,
 554479005,
 599580017,
 688537004,
 684209004,
 656763001,
 739144003,
 688537011,
 351484002,
 612481002,
 720137001,
 739144004,
 758064001,
 554479001,
 739144007,
 739590002,
 610776002,
 706016002,
 706016001,
 747939002]

In [12]:
#Get training data from 2019-5-1 to 2019-7-25
mask_train = (transaction_raw.t_dat >= '2019-05-01') & (transaction_raw.t_dat <= '2019-07-25')
train_raw = transaction_raw.loc[mask_train].reset_index(drop=True)
train_raw

t_dat                                        customer_id  \
0       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
1       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
2       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
3       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
4       2019-05-01  00019d6c20e0fbb551af18c57149af4707ec016bb0decd...   
...            ...                                                ...   
4953538 2019-07-25  fff3e75605ec575be9b95eda1e6557299e81bba12668d7...   
4953539 2019-07-25  fff3e75605ec575be9b95eda1e6557299e81bba12668d7...   
4953540 2019-07-25  fff4d3a8b1f3b60af93e78c30a7cb4cf75edaf2590d3e5...   
4953541 2019-07-25  fff4d3a8b1f3b60af93e78c30a7cb4cf75edaf2590d3e5...   
4953542 2019-07-25  fff4d3a8b1f3b60af93e78c30a7cb4cf75edaf2590d3e5...   

         article_id     price  sales_channel_id  
0         524061003  0.050831                 2  
1         735404001  0.050831                 2  
2         700370004  0.016932                 2  
3         618800001  0.033881                 2  
4         731407001  0.016932                 2  
...             ...       ...               ...  
4953538   751530001  0.011847                 1  
4953539   800988001  0.028458                 1  
4953540   749699001  0.025407                 1  
4953541   507883009  0.013542                 1  
4953542   788261001  0.008458                 1  

[4953543 rows x 5 columns]

In [13]:
#Get test data from 2019-7-26 to 2019-8-1
mask_test = (transaction_raw.t_dat >= '2019-07-26') & (transaction_raw.t_dat <= '2019-08-01')
test_raw = transaction_raw.loc[mask_test].reset_index(drop=True)
test_raw

t_dat                                        customer_id  \
0      2019-07-26  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...   
1      2019-07-26  0002db27a1651998a3de4463437b580b45dfa7d8107afa...   
2      2019-07-26  0006d3ff0caf0cb4d4e0615ee5cb7d268622364d483335...   
3      2019-07-26  000c6b4be3802318b68fe21ac36b119ef6568f42a82f18...   
4      2019-07-26  000c6b4be3802318b68fe21ac36b119ef6568f42a82f18...   
...           ...                                                ...   
372838 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
372839 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
372840 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
372841 2019-08-01  fff613e0adf409bc8acf40c7eabb40f377c7d4f7b12f61...   
372842 2019-08-01  fff887d056fff68679d6e2491588ee4e83e57bf077ca7a...   

        article_id     price  sales_channel_id  
0        740943002  0.013542                 2  
1        773980002  0.010153                 1  
2        752020001  0.022017                 1  
3        650672001  0.007610                 2  
4        740720002  0.007610                 2  
...            ...       ...               ...  
372838   719209001  0.016932                 2  
372839   720426001  0.025407                 2  
372840   713199001  0.033881                 2  
372841   739590002  0.016932                 2  
372842   713774006  0.022017                 1  

[372843 rows x 5 columns]

In [16]:
#common customer_id between training and testing data
no_customer_train = train_raw.customer_id.nunique()
no_customer_test = test_raw.customer_id.nunique()
common_customers = set(train_raw.customer_id.unique()) & set(test_raw.customer_id.unique())

In [21]:
print("Number of customers in training:", no_customer_train)
print("Number of customers in testing:", no_customer_test)
print("Number of returning customers in testing:", len(common_customers))
print("Number of new customers in testing:", no_customer_test - len(common_customers))

Number of customers in training: 542310
Number of customers in testing: 83377
Number of returning customers in testing: 63462
Number of new customers in testing: 19915


In [22]:
#Number of unique articles in training
no_article_train = train_raw.article_id.nunique()
no_article_train

43362

In [69]:
#create user-article matrix of training data
df_t = pd.DataFrame({"customer":["A","A","A","B","B","B","C","C","C","D","D"],
                     "article":["a","a","b","a","b","c","c","d","e","d","e"],
                     "value":np.ones(11)})
df_t

customer article  value
0         A       a    1.0
1         A       a    1.0
2         A       b    1.0
3         B       a    1.0
4         B       b    1.0
5         B       c    1.0
6         C       c    1.0
7         C       d    1.0
8         C       e    1.0
9         D       d    1.0
10        D       e    1.0

In [70]:
df_t.drop_duplicates(inplace=True)

In [71]:
df_t.pivot(index='customer', columns="article")['value'].fillna(0)

article     a    b    c    d    e
customer                         
A         1.0  1.0  0.0  0.0  0.0
B         1.0  1.0  1.0  0.0  0.0
C         0.0  0.0  1.0  1.0  1.0
D         0.0  0.0  0.0  1.0  1.0

In [72]:
import numpy as np

df_p = df_t.pivot(index='customer', columns="article")['value'].fillna(0)
df_m = np.array(df_p)
df_m

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [75]:
n_feature = df_m.shape[1]
A = df_m[0].reshape((1,n_feature))
B = df_m[1].reshape((1,n_feature))
C = df_m[2].reshape((1,n_feature))
D = df_m[3].reshape((1,n_feature))
print(A)
print(B)
print(C)
print(D)

[[1. 1. 0. 0. 0.]]
[[1. 1. 1. 0. 0.]]
[[0. 0. 1. 1. 1.]]
[[0. 0. 0. 1. 1.]]


In [77]:
from sklearn.metrics import pairwise
print("A-B",pairwise.cosine_similarity(A,B))
print("B-C",pairwise.cosine_similarity(B,C))
print("C-D",pairwise.cosine_similarity(C,D))

A-B [[0.81649658]]
B-C [[0.33333333]]
C-D [[0.81649658]]


In [78]:
#calculating cosine similarity
pairwise.cosine_similarity(df_m)

array([[1.        , 0.81649658, 0.        , 0.        ],
       [0.81649658, 1.        , 0.33333333, 0.        ],
       [0.        , 0.33333333, 1.        , 0.81649658],
       [0.        , 0.        , 0.81649658, 1.        ]])

In [84]:
#print pair similarity
from scipy import sparse

Asparse = sparse.csr_matrix(df_m)

print(pairwise.cosine_similarity(Asparse, dense_output=False))

  (0, 1)	0.816496580927726
  (0, 0)	0.9999999999999998
  (1, 2)	0.3333333333333334
  (1, 1)	1.0000000000000002
  (1, 0)	0.816496580927726
  (2, 3)	0.816496580927726
  (2, 2)	1.0000000000000002
  (2, 1)	0.3333333333333334
  (3, 3)	0.9999999999999998
  (3, 2)	0.816496580927726


In [91]:
pairwise.cosine_similarity(Asparse, dense_output=False)[0,1]

0.816496580927726

In [119]:
#example: identify the closest customers to customer A
similarity = pairwise.cosine_similarity(df_m)[0,:]
similarity

array([1.        , 0.81649658, 0.        , 0.        ])

In [120]:
#Get index of similarity (sorted, descending order)
np.argsort(similarity)[::-1]

array([0, 1, 3, 2], dtype=int64)

In [122]:
#Get the items which haven't been purchased 
not_purchased = df_m[1] - df_m[0] 
np.where(not_purchased)

(array([2], dtype=int64),)

In [5]:
%%time

article_raw = pd.read_csv("../data/articles.csv")
customer_raw = pd.read_csv("../data/customers.csv")
sample_sub_raw = pd.read_csv("../data/sample_submission.csv")
transaction_raw = pd.read_csv("../data/transactions_train.csv")

CPU times: user 34.3 s, sys: 10.1 s, total: 44.4 s
Wall time: 47.9 s


## 1. article.csv

- What are the features and their data type? 
- Percentage of missing data, how to handle missing data.
- How do features relate to each other?
- How should we consider or use the features for predictions/product recommendations?

In [ ]:
article_raw.head()

## 2. customers.csv


In [ ]:
customer_raw.head()

## 3. transactions_train.csv

In [ ]:
transaction_raw.head()

## 4. sample_submission.csv

In [ ]:
sample_sub_raw.head()

In [3]:
#calculating cosine similarity
from sklearn.metrics import pairwise


In [7]:
#Ben and John
pairwise.cosine_similarity([[1,1,1]],[[1,0,1]])

array([[0.81649658]])

In [8]:
#John and David
pairwise.cosine_similarity([[1,0,1]],[[1,0,0]])

array([[0.70710678]])

In [9]:
#Ben and Daivd
pairwise.cosine_similarity([[1,1,1]],[[1,0,0]])

array([[0.57735027]])