## Content-based recommendation (using cosine similarity)
### Use article description to acquire similarity between articles

In [189]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import collaborative_filter as cf

In [190]:
#read Menswear data set
transaction_men_raw = pd.read_csv("../data/large_data/transaction_2019_567_Menswear.csv")
transaction_men_raw.head()

Unnamed: 0       t_dat                                        customer_id  \
0          60  2019-05-01  00357b192b81fc83261a45be87f5f3d59112db7d117513...   
1         140  2019-05-01  0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...   
2         141  2019-05-01  0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...   
3         142  2019-05-01  0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...   
4         143  2019-05-01  0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...   

   article_id     price  sales_channel_id  year  month  week  product_code  \
0   743719001  0.050831                 2  2019      5    18        743719   
1   507431031  0.015237                 2  2019      5    18        507431   
2   378447036  0.054220                 2  2019      5    18        378447   
3   657850001  0.030492                 2  2019      5    18        657850   
4   598755015  0.013542                 2  2019      5    18        598755   

   ...          department_name  index_code index_name index_group_no  \
0  ...                    Shoes           F   Menswear              3   
1  ...  Jersey inactive from s1           F   Menswear              3   
2  ...                 Knitwear           F   Menswear              3   
3  ...                 Knitwear           F   Menswear              3   
4  ...       Light Basic Jersey           F   Menswear              3   

   index_group_name section_no           section_name garment_group_no  \
0          Menswear         27              Men Shoes             1020   
1          Menswear         55    Contemporary Street             1005   
2          Menswear         23  Men Suits & Tailoring             1003   
3          Menswear         20     Contemporary Smart             1003   
4          Menswear         26          Men Underwear             1002   

   garment_group_name                                        detail_desc  
0               Shoes  Cotton canvas trainers with a padded edge and ...  
1        Jersey Fancy  T-shirt in hard-washed slub cotton jersey with...  
2            Knitwear  Jumper in fine-knit merino wool with a V-neck ...  
3            Knitwear  Jumper in a textured-knit wool blend with long...  
4        Jersey Basic  Long, round-necked T-shirt in soft jersey with...  

[5 rows x 33 columns]

In [5]:
print(transaction_men_raw.columns)

Index(['Unnamed: 0', 't_dat', 'customer_id', 'article_id', 'price',
       'sales_channel_id', 'year', 'month', 'week', 'product_code',
       'prod_name', 'product_type_no', 'product_type_name',
       'product_group_name', 'graphical_appearance_no',
       'graphical_appearance_name', 'colour_group_code', 'colour_group_name',
       'perceived_colour_value_id', 'perceived_colour_value_name',
       'perceived_colour_master_id', 'perceived_colour_master_name',
       'department_no', 'department_name', 'index_code', 'index_name',
       'index_group_no', 'index_group_name', 'section_no', 'section_name',
       'garment_group_no', 'garment_group_name', 'detail_desc'],
      dtype='object')


In [28]:
transaction_men_raw['details_description'] = transaction_men_raw['product_type_name'] + " " + \
                                             transaction_men_raw['product_group_name'] + " " + \
                                             transaction_men_raw['graphical_appearance_name'] + " " + \
                                             transaction_men_raw['colour_group_name'] + " " + \
                                             transaction_men_raw['perceived_colour_value_name'] + " " + \
                                             transaction_men_raw['perceived_colour_master_name'] + " " + \
                                             transaction_men_raw['department_name'] + " " + \
                                             transaction_men_raw['section_name'] + " " + \
                                             transaction_men_raw['garment_group_name'] + " " + \
                                             transaction_men_raw['detail_desc']
 

In [30]:
transaction_men_raw.details_description.value_counts()

T-shirt Garment Upper body Solid White Light White Light Basic Jersey Men Underwear Jersey Basic Round-necked T-shirt in soft cotton jersey.                                                                                                                                                                                                                                                                                                      1871
T-shirt Garment Upper body Front print White Light White Jersey Fancy Contemporary Smart Jersey Fancy T-shirt in printed cotton jersey.                                                                                                                                                                                                                                                                                                           1732
T-shirt Garment Upper body Solid Black Dark Black Light Basic Jersey Men Underwear Jersey Basic Round-necked T-shirt in so

In [5]:
content = transaction_men_raw.detail_desc.value_counts().index

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(content)
vectorizer.get_feature_names()

X.shape

(1923, 978)

In [6]:
similarity = cosine_similarity(X)

In [8]:
similarity.shape

(1923, 1923)

In [31]:
##subset data with article_id and detail_desc

article_desc_df = transaction_men_raw[['article_id','details_description']].drop_duplicates().dropna().reset_index(drop=True)
article_desc_df

article_id                                details_description
0      743719001  Sneakers Shoes Solid Grey Medium Dusty Grey Sh...
1      507431031  T-shirt Garment Upper body Treatment Black Dar...
2      378447036  Sweater Garment Upper body Melange Dark Blue D...
3      657850001  Sweater Garment Upper body Melange Dark Grey D...
4      598755015  T-shirt Garment Upper body Melange Greenish Kh...
...          ...                                                ...
5219   652346002  Underwear bottom Underwear Check Light Red Med...
5220   809223001  Trousers Garment Lower body Solid Greenish Kha...
5221   755780003  Sweater Garment Upper body Colour blocking Whi...
5222   786161002  Underwear bottom Underwear Solid White Light W...
5223   712295008  Hoodie Garment Upper body All over pattern Gre...

[5224 rows x 2 columns]

In [32]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(article_desc_df['details_description'])
X.shape

(5224, 1081)

In [73]:
similarity = cosine_similarity(X)
similarity.shape

(5224, 5224)

In [74]:
similarity[0]

array([1.        , 0.08852791, 0.03685904, ..., 0.02976935, 0.0310341 ,
       0.07560741])

In [79]:
np.sort(similarity[0])

array([0.        , 0.00281989, 0.00288001, ..., 0.90912136, 0.92070483,
       1.        ])

In [37]:
#sort index of similarity 
sorted_sim_index = np.fliplr(np.argsort(similarity))

In [41]:
sorted_sim_index[1]

array([   1, 4450, 1994, ..., 3901, 1171, 3763], dtype=int64)

In [42]:
#the 10 most similar items to the item(index = 0)
articleID = article_desc_df.article_id[0]

similar_items_index = sorted_sim_index[0][1:11]

In [43]:
articleID

743719001

In [44]:
similar_items_index

array([2668, 2889, 5152,  701, 4957, 4979, 3582, 3635, 4188, 4009],
      dtype=int64)

In [48]:
article_desc_df.article_id[similar_items_index]

2668    601728002
2889    601728001
5152    601728027
701     601728013
4957    728836001
4979    766099001
3582    728788002
3635    671809009
4188    601728016
4009    728836003
Name: article_id, dtype: int64

In [191]:
mask_train = transaction_men_raw.week == 18
X_train = transaction_men_raw.loc[mask_train].reset_index(drop=True)
mask_test = transaction_men_raw.week == 19
X_test = transaction_men_raw.loc[mask_test].reset_index(drop=True)[['customer_id','article_id']]

In [196]:
Customer_IDs = X_train.customer_id.unique()
len(Customer_IDs)

5993

In [259]:
%%time

AOP_results = []
MAP_results = []
num_users = []
timeline = []

# week 18 - 31
for wk in range(18,31):
    mask_train = transaction_men_raw.week == wk
    X_train = transaction_men_raw.loc[mask_train].reset_index(drop=True)
    mask_test = transaction_men_raw.week == wk+1
    X_test = transaction_men_raw.loc[mask_test].reset_index(drop=True)[['customer_id','article_id']]

    #concatenate all text information
    X_train['details_description'] = X_train['product_type_name'] + " " + \
                                     X_train['product_group_name'] + " " + \
                                     X_train['graphical_appearance_name'] + " " + \
                                     X_train['colour_group_name'] + " " + \
                                     X_train['perceived_colour_value_name'] + " " + \
                                     X_train['perceived_colour_master_name'] + " " + \
                                     X_train['department_name'] + " " + \
                                     X_train['section_name'] + " " + \
                                     X_train['garment_group_name'] + " " + \
                                     X_train['detail_desc']

    #subset article_id and description column
    article_desc_df = X_train[['article_id','details_description']].drop_duplicates().dropna().reset_index(drop=True)

    #TF-IDF
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(article_desc_df['details_description'])

    #Calculate cosine similarity between articles
    similarity = cosine_similarity(X)

    #sort index of similarity
    sorted_sim_index = np.fliplr(np.argsort(similarity))

    #find customers in training and their purchases items
    Customer_IDs = X_train.customer_id.unique()

    #dict to save customer_id and recommended article_ids
    recommended_items = {}

    for customer in Customer_IDs:

        #find items purchased by customer in training
        purchased = list(X_train.loc[X_train.customer_id == customer].article_id)

        #empty list to store similarity array for each purchased item
        similarity_items = []

        #for each article_id, find its 12 most similar items' similarites
        for each in purchased:

            #article_id's index
            item_index = np.where(article_desc_df.article_id == each)[0]

            if item_index.size == 1:
                item_index = item_index[0]
                #use article_id's index to get its similarity vectors with others and append to list
                similarity_items.append(similarity[item_index])

        #if no similarity item, go to next customer
        if len(similarity_items) == 0:
            break
        
        #convert similarity_items list to np array
        similarity_items = np.asarray(similarity_items)

        #replace 1. with 0 in the similarity_items (1 is the item itself)
        similarity_items[similarity_items > 0.999] = 0

        #Get index of 12 highest similarity for each purchased item
        high_sim_index = np.argpartition(similarity_items, -12)[:,-12:].flatten()

        #Get similarity using above index info
        high_similarity = np.take(similarity_items, high_sim_index).flatten()

        #make a dataframe
        item_index_sim_df = pd.DataFrame({"item_idx":high_sim_index, "similarity":high_similarity})
        #sort by similarity and get the first 12 items
        item_index_sim_df = item_index_sim_df.sort_values('similarity', ascending=False).reset_index(drop=True)[0:12]

        #retrieve the article_id by index
        recommend_article_ids = list(article_desc_df.article_id[list(item_index_sim_df.item_idx)])

        #add user_id and recommended items to dict
        recommended_items[customer] = recommend_article_ids

    #calculate AOP@12 for each train-test group
    AOP12_CB, num_user = cf.AOP(recommended_items, X_test)
    AOP_results.append(AOP12_CB)

    MAP12_CB, num_user = cf.MAP(recommended_items, X_test)
    MAP_results.append(MAP12_CB)
    
    #append number of users
    num_users.append(num_user)

    #append week to timeline
    timeline.append('Wk_'+str(wk+1))

100%|████████████████████████████████████| 5993/5993 [00:00<00:00, 6666.29it/s]


Number of users: 379


100%|████████████████████████████████████| 5993/5993 [00:00<00:00, 6718.61it/s]


Number of users: 379


100%|████████████████████████████████████| 5098/5098 [00:00<00:00, 5664.44it/s]


Number of users: 334


100%|████████████████████████████████████| 5098/5098 [00:00<00:00, 5535.29it/s]


Number of users: 334


100%|████████████████████████████████████| 5773/5773 [00:01<00:00, 4929.97it/s]


Number of users: 411


100%|████████████████████████████████████| 5773/5773 [00:01<00:00, 4963.89it/s]


Number of users: 411


100%|████████████████████████████████████| 6984/6984 [00:01<00:00, 3812.23it/s]


Number of users: 533


100%|████████████████████████████████████| 6984/6984 [00:01<00:00, 4093.79it/s]


Number of users: 533


100%|████████████████████████████████████| 8212/8212 [00:01<00:00, 5559.92it/s]


Number of users: 534


100%|████████████████████████████████████| 8212/8212 [00:01<00:00, 5434.81it/s]


Number of users: 534


100%|████████████████████████████████████| 6289/6289 [00:01<00:00, 5595.76it/s]


Number of users: 396


100%|████████████████████████████████████| 6289/6289 [00:01<00:00, 5656.14it/s]


Number of users: 396


100%|████████████████████████████████████| 6336/6336 [00:01<00:00, 3206.80it/s]


Number of users: 583


100%|████████████████████████████████████| 6336/6336 [00:01<00:00, 3197.09it/s]


Number of users: 583


100%|████████████████████████████████████| 9897/9897 [00:03<00:00, 2748.68it/s]


Number of users: 1003


100%|████████████████████████████████████| 9897/9897 [00:03<00:00, 2738.03it/s]


Number of users: 1003


100%|██████████████████████████████████| 11093/11093 [00:03<00:00, 3690.65it/s]


Number of users: 885


100%|██████████████████████████████████| 11093/11093 [00:02<00:00, 3716.62it/s]


Number of users: 885


100%|████████████████████████████████████| 9243/9243 [00:02<00:00, 4234.50it/s]


Number of users: 702


100%|████████████████████████████████████| 9243/9243 [00:02<00:00, 4301.50it/s]


Number of users: 702


100%|████████████████████████████████████| 8023/8023 [00:01<00:00, 4632.68it/s]


Number of users: 575


100%|████████████████████████████████████| 8023/8023 [00:01<00:00, 4515.36it/s]


Number of users: 575


100%|████████████████████████████████████| 1341/1341 [00:00<00:00, 3991.47it/s]


Number of users: 84


100%|████████████████████████████████████| 1341/1341 [00:00<00:00, 4126.56it/s]


Number of users: 84


100%|███████████████████████████████████| 8844/8844 [00:00<00:00, 11296.15it/s]


Number of users: 351


100%|███████████████████████████████████| 8844/8844 [00:00<00:00, 11457.10it/s]

Number of users: 351
Wall time: 5min 46s


In [260]:
print(AOP_results)
print(MAP_results)
print(num_users)

[0.028144239226033426, 0.02395209580838322, 0.017639902676399016, 0.018136335209505937, 0.022627965043695374, 0.01578282828282828, 0.019868496283590623, 0.01595214356929213, 0.0181732580037665, 0.01614434947768282, 0.017826086956521735, 0.010912698412698412, 0.018518518518518514]
[0.03853711762682739, 0.03128647106940519, 0.020841649901868882, 0.022698710503588557, 0.02959429208258797, 0.015353366821169851, 0.024033739749863253, 0.02145334678983732, 0.022276402714255815, 0.019049254928884558, 0.021501301838258362, 0.011377236079617032, 0.027437822808193194]
[379, 334, 411, 533, 534, 396, 583, 1003, 885, 702, 575, 84, 351]


In [262]:
#save results in a dataframe
result_df = pd.DataFrame({'timeline':timeline,
                          'AOP':AOP_results,
                          'MAP':MAP_results,
                          'num_users':num_users})

#save the dataframe in csv
#change file name for different period groups
result_df.to_csv("../data/MenswearResults/content-based.csv")

result_df.head()

timeline       AOP       MAP  num_users
0    Wk_19  0.028144  0.038537        379
1    Wk_20  0.023952  0.031286        334
2    Wk_21  0.017640  0.020842        411
3    Wk_22  0.018136  0.022699        533
4    Wk_23  0.022628  0.029594        534

In [238]:
mask_train = transaction_men_raw.week == 20
X_train = transaction_men_raw.loc[mask_train].reset_index(drop=True)
mask_test = transaction_men_raw.week == 21
X_test = transaction_men_raw.loc[mask_test].reset_index(drop=True)[['customer_id','article_id']]


In [247]:
#concatenate all text information
X_train['details_description'] = X_train['product_type_name'] + " " + \
                                 X_train['product_group_name'] + " " + \
                                 X_train['graphical_appearance_name'] + " " + \
                                 X_train['colour_group_name'] + " " + \
                                 X_train['perceived_colour_value_name'] + " " + \
                                 X_train['perceived_colour_master_name'] + " " + \
                                 X_train['department_name'] + " " + \
                                 X_train['section_name'] + " " + \
                                 X_train['garment_group_name'] + " " + \
                                 X_train['detail_desc']

#subset article_id and description column
article_desc_df = X_train[['article_id','details_description']].drop_duplicates().dropna().reset_index(drop=True)

#TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(article_desc_df['details_description'])

#Calculate cosine similarity between articles
similarity = cosine_similarity(X)

#sort index of similarity
sorted_sim_index = np.fliplr(np.argsort(similarity))

#find customers in training and their purchases items
Customer_IDs = X_train.customer_id.unique()


In [255]:
pro_customer = '9058cc9742a41b8e1d1224fe8e8ea25190fd4e6125c1b4a0be2df07275c7f1e0'

In [256]:
#find items purchased by customer in training
purchased = list(X_train.loc[X_train.customer_id == pro_customer].article_id)
purchased

[706268015]

In [258]:
#dict to save customer_id and recommended article_ids
#recommended_items = {}

#for customer in Customer_IDs:

#find items purchased by customer in training
#purchased = list(X_train.loc[X_train.customer_id == pro_customer].article_id)

#empty list to store similarity array for each purchased item
similarity_items = []

#for each article_id, find its 12 most similar items' similarites
for each in purchased:

    #article_id's index
    item_index = np.where(article_desc_df.article_id == each)[0]

    if item_index.size == 1:
        item_index = item_index[0]
        #use article_id's index to get its similarity vectors with others and append to list
        similarity_items.append(similarity[item_index])

#convert sim_temp_list to np array
similarity_items = np.asarray(similarity_items)
similarity_items

array([[0.03733172, 0.03184119, 0.09414912, ..., 0.04126758, 0.05181664,
        0.03746181]])

In [249]:

#dict to save customer_id and recommended article_ids
recommended_items = {}

for customer in Customer_IDs:

    #find items purchased by customer in training
    purchased = list(X_train.loc[X_train.customer_id == customer].article_id)

    #empty list to store similarity array for each purchased item
    similarity_items = []

    #for each article_id, find its 12 most similar items' similarites
    for each in purchased:

        #article_id's index
        item_index = np.where(article_desc_df.article_id == each)[0]

        if item_index.size == 1:
            item_index = item_index[0]
            #use article_id's index to get its similarity vectors with others and append to list
            similarity_items.append(similarity[item_index])

    #convert sim_temp_list to np array
    similarity_items = np.asarray(similarity_items)

    #replace 1. with 0 in the similarity_items (1 is the item itself)
    similarity_items[similarity_items > 0.999] = 0

    print(customer)
    #Get index of 12 highest similarity for each purchased item
    high_sim_index = np.argpartition(similarity_items, -12)[:,-12:].flatten()

    #Get similarity using above index info
    high_similarity = np.take(similarity_items, high_sim_index).flatten()

    #make a dataframe
    item_index_sim_df = pd.DataFrame({"item_idx":high_sim_index, "similarity":high_similarity})
    #sort by similarity and get the first 12 items
    item_index_sim_df = item_index_sim_df.sort_values('similarity', ascending=False).reset_index(drop=True)[0:12]

    #retrieve the article_id by index
    recommend_article_ids = list(article_desc_df.article_id[list(item_index_sim_df.item_idx)])

    #add user_id and recommended items to dict
    recommended_items[customer] = recommend_article_ids



00cc7b20c3598962935bb62755b952a9c6517e0cb869195f352335fa998ac1da
01179a3b2c4f0a9d447b44a6d0e3bd6ba79ac85f1f40de787bc6efbcbd16b381
0198f1ec9513d4fab06a33dffba49746707b838f90ac4faed79986a0dee5c09f
022df8068a48bc81eb90cbb500c05d25e00fd4374948adf4146b0e71164f041c
0255d2ae6c3cb02f410df152c53942f1eb0d8e36d99a35e59581d108fbe7e48c
034ecb394573da6ddec92ddb08a402cea53370cce17a1836c3c7b2fabcd80368
037ec5bb01a1ea87eb873699dc40aac3b4e2bb2ba50a4c0a9b3594aec4a62d6c
03fa7262bf2b756b4e1c709b7cb12770759a60d3c17aa4a3e20cedbb237f2aaa
042a89d95d791e6b62e3eb7dc5d8109bae8fb12babdc3d981c780ca34334a739
047868ff416f0014c3fe35fc99115993c84cbefea12c9bd648dbb81c56a60d63
04af88d63d4d5a69c13278b0b0dc98925e2fc099c1a46443fa0b4baa1f981f42
05118b09ca00a6f66ad43e8cc25a6a476609d197edb265ee6b667f8844d9d899
06479355def71950c7197430f63082a3b86ae84438293ddd81d44fa1ca33bbfe
06b92dd450099becdb5572124300216c2854d21d1c8ac898c807526d5635cc43
07296a38c9756882d70661dbb9423543fcf19243620cb1c7bfcde0ebc4911335
078d3bd8741a0b37c05c68798

332a1bed41529c31c5b2e34de0c9fd70361dca6b6a615a80f7e5d2b405293b23
334e144cdb699b6118ce038cbe25f42174435eea433ae586667e0161b90aac2b
338b2a226055f4613cb48e793b1329c8235572e889af38f339fd1a67ec04ba1a
3401321752c829ef80d47753a49872ba353409fdc2b7d2ee9a060f306d349bb3
3451c42061c9e1386402865075c2b42902b07d70c8e82d9a43d1339731c3c663
345b0f9147215ef7e18d2117cb04eedf9c488177d530b43a43c5c86d35c63bcf
3467b238dc8d91f391f27e54725a52bbe04137097c3a3ea1ca3ec281b8dd5106
347aca487efe48b4020bfa9ea879d2ab3a88f332196170eefd5180b55aefd0ae
34878678f2b420f3010c314439d6ccdea581ceeeb06006d57f70a76dbdd13b61
3554fa2852c829611a2c8fc66f9eb047d73e588da7d433d331d271864d157f84
3639368aa6d65cece5d44d6a25b523045fd0838914084c02b3a1dae662aac3f7
36891c8207865bbcbc92b7da139c6318bec0856e807d9eb1570f4ab38f2f0a1d
36bec760c3d1790bf32db8d94e09729bdff14300e718a1cb27b87f2fe43d7d26
36ecd9f20fd80565a1604c510a3a20b7f70216b11e96c17d3aea38de6fa2131c
373d13886ccf026867a5c1c34cd4657525fcc27fef40b0718b3a80ccfa6913c1
38450461d9d8b685578f5393c

6136e8273f71a2732819afb3d0cf89f4dcd1f6d655a417ea4a70c0e65093c4ea
61387c9b71b2e2713906cc1af35fae169151f5c56e08bdafab7d53f76560addb
61c32e9385b9fe8ad847b1a9f60ec8c82947b161e792e99161c6251541370ef5
61deef5d0cdaca84e79118d1195ea97849cbb507fc8096ed1d7f1d7ad1eb9140
622af1b44d843bb68edc4e5094f233e76158214fc98bf9fdc91cb5bbd3c74508
62a45b29d0ed5e6dda358fb9b1c67259ff23da60d2fa0735c2f91d97ce47aa38
62eb7f6a247863fa029692beaeefdee2c64b1c34c7e865b981b5a9947e416198
63328c4a34c5c6dc7efd90df01252f5252af24bbd95958e8280cdaea4008e696
633c4a750daf2de331507e83c31f6ba9e50635bd4f4715d470822e9a03a8cf20
6365c47a0190be82ad9d120c29c163ec14d6059cddd843b3a5f2975f55641b2d
63cadd83ceb7df9be539d9a0e058d5a8dab31e2c1d69f2367e4fc94adb896f75
641a59aff760046e52cb8b55a16e05604bbdba94093968f26f18565aa14d5d38
6446cf40b9629a51d307f18676513a06bc15e37d4bd03ba4f9f13fa174c371d9
64ae1891f9595ce1ca0d94f29afd9f23a78f79feccae8e9f3ebeb22e66a3bcb4
64e01ae9b418bb0f937ec0ddb340f56a320a7e47dde0ed42bb7dfa31a70884ff
653b3736628c2faa09d745023

8d59e044e3c2a1cf754b7bacbc8939f09eca58497a0fc1d72928a51691f012fa
8dba102ad9065c5fb1f35041e60526ddb76b8dfd13048f4a112c85f39d843db3
8de939a2296299204ee5fff3db349d871aa76b82f1b405d368357de581e4d8b9
8e02609d10d12ddb67e8c3d711fe3e9eff09b12b9c71833b8106aa08e61c51f8
8e5d8d6d1e426d65be9d330127bb4120f0e1de0d356103d340e691ad44b9335c
8f18622ca85d4bd9847359e5d56a64e5efe78a9ae81993d0caab744009402f72
8f25da62b022276ad6ab05c0a30bfe5d57fd902cdad1276c9be64b3f50147356
90ef4c009693d3b4b36bad1f0cab9d7a665f6ce7a0cdc981b8dce4736090fa4e
90ff618e92164bcf7d731d009fa218110e8f5ba4d04d30d87ddab3d4f37fb3cb
9141f3865e04f24fe5e0b5d33045da2935661703597012c431ace267b11682ff
914af4497dc8f58b4efb14688e536b293b8d2421299ba5d45e9b83977d5dbbb8
92a87c176005f0fc615cda0d2bf811710b966e35bd1c47e53b9081d47b6d4d94
92e55649e0bd7cde18ced693590542a97081369f724f1fb57a7484ce7214c573
935cfe6d84df55a3f70556d10ec00de73b5f48b834bfc4ac7985647aabbf07af
93b1b4b7e05fb682b02a4358410eeafdc463b1289f43c2e05db0b8bbbe3e1805
93c2232f5a7d96fe10c001a87

d8ddef9b94d9b5c6a25689f1cce6e909426bfb5195ecbd29e39913d92234ca3e
d9c3c3daf3e1d041056669ee81706efe4bf3e6605a3554dcb01a996ee64f0712
d9c847d283f3107245fa2e9ddd6557859194400b50d1b43bd9f9cbc7d4dbdfca
d9e48ec55bea24da8b87a3ea85aebc91d64208e390eb9ee1005c6fbd82fa2d29
da3c828856c33c41742cf0378ea050f4c807d3c4a8169b206cd01f9410b8396a
dacfff48c6722163d11fb65bd5d6c0c8d19462823b376573830b6d27aa14660b
db6a2451928e49f08e867ec94c497f972954b3d46a9c921e0826400c08281f97
dc6b5d36254f1f9d922f1502a9c1bef528fe8c0a780bdfbdfc744e84c4cbaad6
dcb144330424a9001716e6a9b4914f26a929986893ce2c79cfb2e3b05628f7b8
dce84f1ff6ee22ae1a4683e0efe4293193fcf03c1f3a241a8e6dc0eb4c87fc7f
dd2ddeedc6fbe1834eac0e443205e234ac0edf9a182d8ccb8fb9432dafc0b081
ddd98228a86748c341fd9345a00d8f174774f7b0b05d7969fb65e3e76e9aaaef
de72b9f6f703e7becb656cb0457957d65f33521dd307238ab5b507d5ead1487f
ded0c41e1d330b3db5fe364cb29b88c8dd5a98772b66162d5c6166959d826ee5
df39fe72bf6379ceee1eda3cb8afc7cb60664ff4888799b1b6684a2ac9be2eea
df3dabc46912064e3d9ed5556

1e7c76d7f0238515236ebf4966fe80969ebac7bd28f493ba1d7b58c12357ca47
1eb574ae4e03614c176356a8c24bf86bf75bcb1b49a3518447279ef3477a5bee
1eee967effa2f86ebe5f7153815f037f4c876c6fc799fb2038c9bc8333b7f28a
1f0bf009430791050987de73524f947287476563e6fb54221727a10e4bd2daba
1f3115ec7e8974d528bcb914e034a8c7be37141e72b92b8035344996b9f379d2
1f638a859f4a5514e3a3ad947fb0d0a3014ff019f3072da0d9953f3bf113c2b1
1fab35557f26b63d856769764ab86847c5b05fe30d326f8d49e6dae152fdf275
1fe9b761a45ca3f387ff58303c80c9c67eb63206b1e285ec9a4f9052bd58aed7
205e5d21e80093897e40b90faad4b228481aa6f929ba8d252bfbd4a07bbf2b96
20c9499959d9601b7029f74783a4c16c786f64b7f74aa6fd9619a0d42653b10a
211d7a48b4a4a77f98b74b9e9d6496530803c8eccc6b6af89e7818ad1748f207
218387d84709cc77b4d5b653cbc928af2b46264db025c2ae6db55d27a38e60ce
21926cdf83c8bd419b7d5eaf65c69ce60e96841207f90344aa5f18773b7a8734
21c7d12bccc1539ed9d6be997b6f4b174c48d0dea846c620605325e874b7232b
21e34ca62bf48270fe9cb9be340710e729ca098755d784d7c93bb8de4713e6b7
223201caac5ff803b810c8193

5ddd1ec95346f63705b2f8eda27c63f68d6a2c457c5160cdcc761d54b8366095
5de78f82fd8871e3aeb8d0ac5d9b0d944dc34e715138b1e509eced37428d7732
5e4340402c2f3546efd3379eb6771500bef9ab47696dc40a45732cf917396f9a
5e8c1c17fe8a50b9d682538cdb35402f8918a89b2304cd7caa61ea6f1b2776c7
5f0b55ae68e06cb980ec650b344f349ed68039ecf02ce39acdf19d9c4ef82df2
5f51565f5941fbaafd37b7ca0c2579f586988283cff9d8169266d264e9f7ba12
5f7fa8755edc8756e3d8fbea45ee97e863a3e3ca712204c186e79d07e5c365d0
5fe76b51feed0ed79a60b9b97b2d595f758093362348b5a147e7383b0c451519
60b113fb4cec2779dcca364dde532efafde5ef14ee38ffff7dd5e1542b14c328
62c2c3d0ebffe0bf28ce678b3e913e3985ead511ab66d15d3f00507c988ee4ac
64a801f6c47218aeb511e325c2cdf8032507f3b11d82c83dcf05990c7e46cecb
65823a83f4a265cc83f4a7cca552b902bbfe674ec98803c10b3a4a7a009f5eae
65a0e78c92cc6ecbd2221594570325f12e7c89a827d6ab5f6ff58c399acb276f
65c68fe8d31f83881fe293455b1e6def41fe0a83195a87d13e40e1df5b046910
65cafd7343696b50f041645658c50b2864a83ba6ad8c5145db5a07d2411dbf86
65fe54e11051021f01a5679d8

a871325646be69069e3faf9ea2a00d14eb7054daff1f5683ad6eee2046f37d4f
a8c50b55f8c36700ee7d0822b57cb741cf66fd7b3410e87e65ee8be6cf653d92
a927eb4c100d9eddedfa7193982d61b946b73f45ed038596790566f758468ae0
a9383f055d24c3cff92fc15afc77b163c1a723a1f8d26b997cd8cda8ff8f69d2
a940ec6644e0f6a36b60669d3d69339fdf3128c768d0e2d8c8d91494be58d661
aa927b5d602b0b89980ff32d810ce0550af3be5ab63cd69090ee18b00bb07f51
abb15cee64c5fe82d784369a28b4a827cd582b17707dc88748f5b3c71659479d
abd72b5cd9a302c7d5b2d94143af54e5faf8c6a4d08d9fd964484197607de201
abddf5d70ac1535e61bccd8e2dfee108401722c705230d9aeb978aca8ae0de17
ac6833df1d76405981a3c2e7c5d99712560508d506e69e3e22ca35cdb25680c3
acab722134d7c9138a24e6b307a464c285abeedb3dbfaec274266031be0ec913
ad5c251c158998b53ad46480b01eedda30d3e41117014aab3977cc2d95a23954
ad64bfabd93a66ed008b7f2bdb8a25f9b0695ae8d0b9a1aeac2c681464e152bc
ad72fc8d4ba3578dd9650e5d3248d960231bf5f83a98d0d3b1b292919bed75dc
ae04cf4fac747c64025163aeae1e1398bdd4db3975b358a3efa9f91aa44ea46e
ae200451d10f352a06a632a36

f3535d228dc3e627adc5f6660d961d8f012b721abe4f37e1ceddcf856ae7aaa9
f387b2b5405ee17f1cea31c1c4853e18dad39c855aab277865aaa7648be6f861
f3a05bb636c3c7e1af0bb2409815df0da53b6ff736a02b9cb139a1db77b65412
f3db490e62a0983b87b787ea62278151cda45de4ce1af770c8ffc52548c7fa3a
f3e84f28804b8db0c1c3e45a685fc40ba012348da3ca1e389e1b3297626b3583
f4181b9217270f97d7697e4e1f52945958fc089932cc290a3563af5972dbe322
f4284dee9d38dd482fe1e53658db7d07fc65f35f44052ebaa50ea34b5ef041c9
f493a5b349847e2acb8ad91629b8d801a958af15914bcc5cf2e083b5f1d16065
f4f3803e3324e29910a67ebfc2d7659c95a9c49c1b704892298fd7f6e94e56e5
f53de2c36d8a9e077ff405c256706d58f014ce5bda1c181920f698dfb69368b5
f63d70678262fb6f4902805e40a5f30fd72c6dbcb4789ea79d5ee1956e5587f0
f64e301569e56835f661a287792ab54c60707ec3672d8b0a53b02ede673cf418
f6d6bd1335d9cdb32e6fa0670cfb93c64579ebb41e7314a9275cc459897f8384
f70cebb5f4162f7c3132c7cb136501187f6c1742be9b44202e95131874b3a513
f7370302998d4709ea62df6f353620715472fe37055868518602293ecf398154
f78c4da596df62c10c1c02a0a

2cf7ae8a8d91be91868c27a567e399dbc565433a1281fb4620f4108851f830c9
2d11a2334a917b5f8adfbb010e4807d41d396dc12defd06a310646129ae5018c
2d214d1d6b821cba7256b6d71dec5b0789e8417c8d4f5a2281c555d9b89a6cee
2d3c6493aacc7d8552b6489fc46e343ce66ecbc542cf2b462860911d5bd1e328
2ec87c311551146596579337a1e3452ef72c2d6e558c21149b031429ecd77912
2efe73faa720d54c75eed45faa89048883d6e13760816062094ad3a7a69047da
2f87e7be6832c2a50b13a1b9a3d8fd9cc7c2cb04e8d4e10e31719c26100436cc
2fd67fa3ac277e1ffbdecdfd905f9ba8366a515a7dee63f206f0ac780ab0512a
31806f33ecc3030960bb27f07efab92a6a974afa3e759c91f93507ed825e9fc5
31a46f9c744c74813bc28c9263c3aded25913d4176af0c90434f7828d8ad8f3d
31c395548b84017d708627b9eac4c20e1cd5052bbe0962ef2566bc62e29b2690
31f91d4d15cda86e6a8825a81b204a0e55b357835b057fdd8f719919bf583f4a
329ecc3f17c4db2a5118fea3118f3c2414e02dcb9bc434c6524685b5fd80bc89
32a421e3bef1f04c96c7dff84d3582c2d809be6474a7b496ee792429378d73c7
32a9c2ff3a078c3703e1b9aca42b7d9d7ff70aa338159b7a5ec610b0aaa3f881
32d347b2066870e2c0ea06d68

5dcd244c9c6b7d2153ed77c46638a3c5407bce24fa65b0b5b5d19417760cc4d9
5e37843195dfa545342b67ff1045b1aa2dd6d148b21ce7bb1e266a54738dd153
5e45562fa749759e9705c6691640bf304a8441297c2fe68914ce6c3a79dab430
5e991ab4f6ddc77460d9343ab59fce3d2ec5139540a6cd6c08c38f5728f5f10a
5f12f11e805051eec20e3bd3a9089c694a9bd7da25013f8b083fd18401e40f64
5f2ec12947d0076017268f23ad3745ac32d65898f0aaba03346a018f8ca012c4
5f5792a36a4d0a3f47bc48c867fc98ce7930f371844f998999627331e4c93713
5f9a5f88e0e825fc5e5858367f88da581b687597e7e3cebd57f03e01f4b8f5cc
5fbd6c9a92695f3604aec07e597981506f4c54c0f22492592fe44ec0a626df46
5fc1a3ead860d85f9144cfa8449400fafa415e36484528b9efeff45a881f3e95
6060010f506acce009a6d17b40b626716c80fc12da938ad8e44cbad22c10ba5f
6061d151b5735267a14b0bf77cab963315d3d6d0b6772834ba6d31c9be67587a
60ccb45cb6523967c0fff6f1816d5dd3727b682169bf4f675a12e72565d1c70e
612dafcfab41d9166c4bb8a92f2869077e256c9c8f032536dfcac94e11880df7
61460834386f9786cd997a8d8a31002a32b8d661eb6128a3d97ccabca0dfa0ea
617ebde4d992f0efd2d59a12b

8ae75953edf5816fd91d497ed3e91ccec8916816025ed42132022cd0c50091a7
8aed54073352d9f1d820d0e61626a245dea821c7ca0f31fab94c3dc9eb8f2785
8afaf1f0ad95dff6b8ec9633dfa42862984d92d0f637696f0161c0858e18a75c
8b797bccc96135e4a0547a907f30bfdd5efa1cc8430f91ee83935b5a885e94f7
8bb668606991653481247da394eb2d69a705bbc5c0e8cb8231445c75b6f6ec3a
8c4b4526a5c10f1dac42583e661f059329bdbc85142fa5f3d92ec18ff14ee202
8c8de6a49083e52d17ee7549167ca902c3aa772623511d50df591f221bce2b29
8caa9696d09a21b72d9a884c6b0df1bcb8d9b675a6cbbcbde8c4c872b898ba40
8ce7c065937b9579f88a70670888e8535ce7a1e46bdbf49fe70958505aebf001
8db18116fd93634ccbf73ce87fc79037dd54e50373b9a9e69d509f5227b69f47
8ea0b487ca6824cf4751d5310c3cd71f67ef8642c144d8570560d213b6fac76f
8ed5f8f8fd08b30f9c3abeaaf3943e30fab0f892ec69a899d4341a69b7a7c587
8f69ccd22fe5105e4f6d8dffe3c2100cde638bc3c234938778bef0eb5be3d34c
8fb36f9dbe52e0119a0b62c4d8dbf545776b8a757e15f581a0e199640c40064b
8fdbf1158138c7beabbc9b7add9e726e50efc89a09d942bab7ee69d0295649aa
8ff715efd8ed076a4583d5158

ba8c7c760cf0cf3707f270dcb0538719e4145f5f556e91b1989a8d4772906130
baab809755ba1a5062acf54e81ad76c418ab8da4a61d868ac83e56b90399a493
bb052458a41f0af5e6878caef53c172c9a281fc0190ccdfe07336f37701a6fa3
bb97518958b4563ad965d6e5bc24d351c0f6ddf47deb7db05c37569f6e085c81
bbb60c00ae4ca51dcd5fc3237bdb039d664aef47d8e10485be8f66099f97af5e
bbc30e56f5b7c1bcb6c7a8e394578f3a83fe2d9eb2e478976ecf96a57c42c278
bd0f128014157d45455995a5ce50138c962997108a5efa7c51f2a766934eb143
bd1a2cf3226f8d127f3e16dfea113181e81b2214810df31f9c16a3e75efcae75
bd6ee39403f6fed6b721662cbaabe3e721700218692bd337ea3287e3d57b6776
be27af1a520713a8e2b2c834476be731bd0036b0453b240e1343b888d485b781
be6aed6cdb56a8b0eda72dc60660f5ded84d87d2cffec6c8f800a8e4484256f3
bea3a931ade91d85f529c183de623c10e33e6c3d2d4d9fbb2aef595ebaa26e34
befcdea124394c603b2c07f73aa1a575b442836b56d830c43405898863cf4ef6
bf305efcd1e3496ceb0f6cde098564d54c15ca47e11ada0a8754dfdaf137a5ca
c0721f51df1984a350e3479a68472605c8c58184005db857528f14b2c5893fe3
c08fc6e218e5c58d24208152a

001ddeb8fb74fec5693116da83b488e05ee9a9e179f3fd1ff67812cb511ced72
0056238bf79efd3e95fc0ed4f4c01c018ff088544fa010b6e75f9531ef64554c
0064cd1ee810d4caabd1182a8f177479b82b18961bd76b6cace9ef1b7a1ba292
008d2890c1aabc017ffbcef1d33b50828e93a6dc65e50c32d978c54da24192bf
0090c0bb62e94f069ee7892db19d2fb546ff3c7cf7b79d6bae8fde9e9b88b2d0
009b99bb7957f83ccdc690b490c38d14c7412c12f224f61fadbb4f7988daf794
00b821ddcf1be1c21ff7cb671a1d9b71df524162fe3cb55b5d2144153d0f4a3b
013fa0eeb73f8e78a5dd1b2276aad1c2fc81b56e7ed55a0bbd04c97792bf6931
01466e24da6f5302282628f64841e2ce08e68474619ed95bb957aa1565a52be5
015c0997320cce8938847f352ca12ab9dcc98c48f841299b498d3e1f59365429
01ad1f4815633e4cae6e47251c41776f962c42bbe133b262f8768787df08cd98
01c0453b7dd5fa8f61485b891356bed2ec6377569e2f26073c2be04598499582
01f5cb03573a50969cf0121c815fe8bd7c4e772e81ef58aeda8141c3375e4b8e
027a5cb87cf20801ca104ce2c7f999de0778e7042b7e24f150952433f2eda6eb
02821b3310961194cc3a8fb105a96787156340fd648d8f902ceed524632ce32a
029978465ee7aba0cfd3ce57a

1af546611dfc989c721778a528ac99e8fe5c7595437d3ed89510c1033501df6b
1ba4442adf9fd9fe22824404a35093835eb71d5c2c81882e69a995e293b77496
1bab826a132661def4106be8e420f2ada16bb820d8e2404ccf33e2d5ac60d1c0
1beae3eeb9440097b0dba04c1f6e92c845bb12e27d395ffe35d905c2774379de
1bfeaea3aaa9e4781b505ab368e9d948cb1e99367134550a84126f63d6f902d7
1c16464f5e04cc7a6ccbe0a53169692f6e4084a4eee9632346eba38536ffc684
1c23584c885f1acddcb67a192193d5d62a9f0737ac43b0d40fa822ca8a7fb315
1c314911505f22b9397b6ecdf2383423643ebda388d93781ff2ab86680214d17
1c65286ec4d120ec6b408ddb347e59273441ec0ffa77f22b8e5ecf5f557a4342
1c8e5ff13d23b008126e7b351f4fe2d8395461612745320dd2def45b4240da5c
1c9aed8c521877354e6fe0046410d16cfe35476edd9992199d8a5c13f43a878a
1ca2e41ec0f94106e1fea405781d5a801ec555264ee2171bb4019ab25bbac7f3
1cd2337498a7d1a3838dee5b7b67b7be41f75dcdefb2bfe65397d592f3dbe1f1
1cee9946b9e798c32225cdefe4df8c6c1e3993052faea8ec3e6ef4837bd10498
1cf942327c94e12d21e8b2d15943e0023a2674935d61fbba37cf5c8cd1128503
1d18a57b2f5adfb0d9aa749c1

3ad67a2ebb86c1f0f32808c3bbb062539a2cdf1a7d2fc72e465294b7c2228aa4
3af63fb6176e57de5c8b3efb9d3f66f9005195dcb9544857582cb373accfaa0c
3b3f3969ec7041227c02c2f4ffceeb4d48e41145cca2918fa0badb480f4efc6c
3bc7e0d0522d7383f8e21a48a99f891d116dada2bf5909f7517fee1de1142828
3bcc073b71d800b509ed81fe274357614a313f7a0ff4f404d53ed39d069ff583
3bdaad3e4c5f80e8e1d0eb93c5740592dbe854cd9a50ddadf97ae2614c0c1fa0
3bee44f7e8f5cb7b9faa2aa97d178258b2efb34afdc8066a8e7a38d7b10fd9e3
3c432c26d4b70d49ecb8eb3c2e57cec68c9cd903ca8d94597da1c10ede71ec8b
3c80289ead1dee23bebb73c7214fd92d42eee378e8c0e58f3c5ffc167745c023
3cb7f2875a61d140ab29244d81e6fe9a8a7a29e4c18025f546a3da95f7580de2
3ce957244ec2b5dc449057a0c442b0e120f1e5f9a6d1d21f9541a2c7bbcc47e4
3d064343ccbcee6bd24f19d1dbb0c0120b5ac532110e570606c34bcc99ee5580
3d36b0e3698f90008f6a0ed6b0fa4ac21747d4292bfb0bb66c3d12a21d38a734
3d7719c1cb01d6d46ea8b152f360b9757426a8520755edf55b12b4cfffd3679e
3dba971b8f69cb1e93b5b58e97125d1cb42e8da6e0f04eac9c8baadec7cbccbf
3dc52aa3d030844dc4b075022

510e25007a50872ebf90fcc8cbccd2c1df6bc657d89978c4e8f75a506e145798
51371364dee97db2cb572338dfc5fd37aca86a576cb72441c22e71b06d654cd5
5159c1b3434e804fce1e8629ba2453018d87174cdee7a5cf064197c5c379ab8e
51ba3cf2fa4cc70a58921f868a9451838230dd6d694a3d08e892220bf6da9e51
51f2c50c3b0285c2a9b68828314976afb5356598959126ff9c1854b1399af179
51fabc230a8149fae18c299557429753bb43cc8989856819340d9313205b8d6b
5209b2442c629860e043cb6b00716e06894113822e5ace4912598015cd6a95e5
5213d298f45dab1fea0c8459482a18114d1da747709b0fb55890f7308e53c6ac
5215ada36b22f1ef1388098a7edb726e28168c6dd00195db14895b04c76f86fc
526c7a61371b0d8bcf3d9750cc41d4a41a7edf4c0df9ddf27d7652c55be76e6e
531a2752297835c66025fe24e744b0ac51d3c4c2343370b79973540778795937
532dabc1b4170d6fb8f1f38eb3e52d667fb10e1b8e44f4fabcec4d67471bdb93
534afafd2c52f60d3a03c0e990a443dbe4312bec4795a4c55b79bad18685bd8a
534c946fa0fc8872bf30ec7e6b51535e01f43c6c597f211ef025c72ffe6b9fcb
5393575c0e1513369fc5f45e268355f9b61bc2759dcf7ae558c466524a4eaba3
5394e3d7f0614479755a02085

664adf3888b95c0f825f05f8594c0c2b1062d5ca520de5b0f23d705f47ff4521
668b99041514078600e898de0e3ea2394ec6228aac17d72e415ac661b50d6a5b
669e44ac99c4f68c0d3bd1f53c0f7ead149eb002af0244266e19b4e377583f36
66a99cbcb80c9555a05352b20ec658e4c61050fcc2f984d9ced2c878588a9765
66dfa4a0f080ea37b41fbd9c745eed100c2c513eb637a13e4815d0d765f30f26
6709de6d23956c89f0991f1dae65890e0cbc712874b749dfe7d31f7e84a5aced
672aa1dc6631361fb3b18c9a4554c1b6656f1d52a9a70ffc86be612ba46bae2f
67ae017c0916cf40513a6024a66f9cf054fa335e732b40fdc905b48cdc8e4bc4
67b77c48f2ca67390d65295d398749acfab6f6f5ea2b6e5a3372e394c851cf3d
67bc0e46cdf91713b761ebe2c0929a08677957ae5c60bf8fdfdbb0a177119e96
67c4c53f73c30d54145449e5990938476acb7d4322bbe71621570b9038a1800d
67d8151c56693954994700d0e65210e36cf65dfb197ef806752854794f75e61c
67deedae069ec34d96e83e5b6cc0f2d5f1768bebe4b8116f264da2281399addf
6845bd8736ccdd075ac2b78df18a3a66c79bb477d28d619fb50f38cb9362b72f
685e19cebb20588aa31d369ce5f9006202f25df60d311de1a1985d9c394326ee
6884d5c356ebb2dffabeeb889

86b91f4484dbfe5c44179bce028fb10dbf9cafca7d1507d9e6aba365b541ac9e
86bb11b89b70bc6105f83938d9f19b65fa8bb0adf44c7653a9324d3953d6b5ab
86c72fa658a87aa0afe08233dbeceb39e30cad7f6c83cccce54010b524860f42
86e3f822b21ca989aa18f628bd0628cd4d57d6498a66d796ce0921d19501555c
86e91fe457399ffad6f227999f77bc4e83d089973316f75fabd711231b1dfb3a
86e9ea3d350221db84d9fbd15aa37a4456ce4b5ab8af94cad2715f902f3e49e0
86f0fe31f65b274515d87a982bb6b36e90adfcb8e4402acb8bb77865e843e724
870cc146d184b135b062857b0ca470f96f988d328583d9a72c3c2218a61ce1c4
871bfcd8b7f21e2f751c42c64b3b92e29cf2601e56f9c668730faf8af0e2b4fc
871dad4808720145036a58f970a427bc23a025c67bec65fb3806d8f92f896605
875c2b0f00f90e942c7c86379bfd0e5a4c2165df78a13efee4a391b96c0cd956
87c9bb0609edcee6d3e6ebcf3acb6bf632685e26e0b6ae149eeeb04136226594
87e3f0b2c72a92cbb408a4da3f0f89da2e4cb1391baf17daa6bd780d9b1afd99
88294766541bcdb4a25ed74c33e7b3699f2a35d5ef7d5940fb86bbd03fd8481e
882bdd9a90cee1fedfa021996d463c3931c64e3bde45eaf053f1387a98a2cd0f
88394d091765ec865984a23ed

9e1e875b460bc4239c7b25b1ef0133c4a0ee78c439faac865cf221aa5fb961b1
9e3a39b738b3a1ce9eff1a1fad462c6edd53c7fc5238535ca8440bf008776778
9e49d233d91963e5ce66cff5321f554405c547e86282a597a454d2f08a0000d5
9ea63494db7708e119830c1e2e49373dcffcaece64b0e36d3919cb546b9e7909
9ece8568968558350200c1150b49d395835ef1069668d08b4af1caeb2d2d93da
9ed61f88f42d143973ecd4094f3131047045ca683e16ce68ac050015c9fcb76e
9f078604ba0cdc2038a55f112efe89aa680fccc00cf75417624c7937a2a65337
9f0b4d88433d1a5959192e25ce44f2422d6d74a9c0a0caa7962b651a52be5123
9f1765574fb4a60f6f89eafaf2aec38bf179ebdaf0622c12a84aa559660b6c04
9f5ef4a5f7ef222f61becb812f798bd9d79fee587e89608f85f0b5ac337ed912
9f6c23280232f1ed6f1d8a68f6dc0de37d9495b6ebe4bde8e93f95342d49c3b6
9f79682c6430657c7294cc98d84cd0cf50de2e6f6e76233aaaf2df34053bb232
9f79c6cdff7adf7d9da12bf394b66fa750a7aab46ee70c4673e6564567ec3cd2
9fa57003fb9cb8ab88208158ad4e1e777dedc8dc732dccbe5fb19014f3b5b4c6
9fa58f83ca4aab35894ebc636f23a45bc9fb27698ac9ffad548a4a42cbe5d14d
9fbf0ca286443561dca119c4b

b34f1609846ab27d52dfce8057701221e5fe087879a0be55870042c7065673ec
b39f1ff29daa799228a8960e6e2a627ba43685e98a80fc54a317ad4adde8eccc
b3ddc504a589a1e83bc85faee1dfd5cdcf96e57bfa436d6c8e00d379d7c905da
b40801ab4d2088726d78c113e21ca788a6f064f7214ffd1bb1aed73b439082bd
b4474b62a271efa420cbc800313db627e0b042ab52d24501f1ab716511dcc01c
b45e546621a329c189e09c3c97311422b0dee14b02af532b5d72cafbcc7fb338
b45ef9cea490420d42a76b743adde7d8981baf6392c13f22945ac9dea1e9c6ae
b4af719b49074be77a6b2fa4d7f353f4bc100c1e1f3386f7111c568d36d4480d
b50dcec814126077ef27124193ffeb50d3d8c39fb59a922a3fdd94cf66071dbd
b5183b8aa2ef9ab8f2dbe59950e6da1180574d2bf8aad629c51d35074f7988e1
b550336d6fe09727529b91e0b9a600dfff0dce09a617df750686b07fe9cb6853
b55621b458981287785090e001d8877337cc21984d66efa89c191c0376f26601
b5564f2271b2b9603b699fa9fdfb22486d8c355c626b91fc9b0d72658f6c6f0b
b55a0040781f2ab7bcc21964afe99890365f894d40b3e21abc870a41e3fa51af
b579a6a2b00b019e096005075f216eeb2ca1246c8ba6b9460cdf8767ff297316
b609d0f052cc548d72cc90417

cb0f677558e689e3e19f3a6410a59044531ab0c3f94b521316ea2d01d388090c
cb3586b428d4490debd4dc03cdffd05fd9bc8ad38d2254765bbf295279737f58
cb419b94793b847f513b01367e259a718353f65c9abca7ce11579fad324627c9
cb5fd8f8468027c309e268cd9627079583ad1159a07fea04b478b74247a2216d
cba1b044918a6b30f1e916d760f64c6bc657d935c73120127ffb9ca7f97be4f8
cbe8ce63b2d29a2200bd72fc581d8cdc8e7b6cde47249ba11eca4db5075eef57
cc13e71e5e71a4cd671c12987fba330deca72bb7c880a90b3ca9816471f74991
cc15077c6d15401128ddf66a2775f0b8c4c1b8130493d426400c9a5784af740d
cc511d4fa372c604f688f3bbdbb722d95d800e713d895f65428c31ad5b3135c7
cc60c74bbb80b203047911d4d8f7122f7bc5b0cdf6d99757f3b287f0ae76a9dd
cc84abdce0b622a508aa0fe7b15f3453e00025faf8af0f15150bd17748045c69
ccaafb9215c9a6be3767e022a7c3f637c8557c497b13f77815ec1e1904b58734
cd17214d666fd1941828ee521e30c972ad04a49281e1848180d2ed9e854239ae
cd27db360a1e172211a0fc7677e4f0c13aa44d9707f44f0f98f375ca386c851d
cd3a6a7005302369ddd71f71cf751fdbb97c6e5350bd19403325ba33dfb2ac45
cd84f3c973e8ad7a1467735c1

e00c9a9afc79303d24133a20a2b65c5a6ed0124b37b1726d2290df440469384c
e01d27c2fee8c21be5941797ed207ce43d132e6d4355904e05cdf19e6931d24d
e0845616c0c71d466e05ca034185387a42e07df011192d3978eadfa177240fee
e0907491e786bc64bd498ab35c7c63051175691dd55f07be4b1e7dcd531ff91b
e0d41a04f4f1ef9e8ce9dfb12d1812ac7b8103f8dfdbb8b55f7c612856d91cc7
e0fb123ddae6d28386c9c391f607dbfd9037031244c105456f2e72aba1a7a7ee
e10adcedae3c79321d34a62b02e8a74c62d336d97bc79be7f1101d8150b12d95
e12f5192b5b16f4466e90c534b5f31962811e06c138cb80b86bc88da40800630
e19886c918a6fb16b25163d2aa784fd205645f01110cda85de5003a84b5d2e04
e1a438e2906684d0affdca4586cc908a9fa88532f277b5ca688131acb48a45c3
e1bc2aca0448a2a4204b02fde333798f3a2edcec1e5b6079e623f15232fabb83
e223048bcf853db937408e03c0f89787bb2227f19a720d16eb9460da392eb381
e235b96b4102c65b6d56bb50dcc9f37c01f81fc790757ab53a2eb71285a262ed
e294c40d8641af4d48d5df64318670af65ae9b593dd9b6f1227828bbef3566e3
e2984bb486a187cacae3818cda0192ae1193e7d745ef9bc5fba27e9b0b400d5e
e30fb66fab86b1e2238780a7b

f658120afa16208791c3b659486302479f7c12bf00b3935a12e14a2da9d6089f
f6d92125473a432c6116945ee26f3292a7fab7e48076fe64452f1c3e4f9cd2d3
f6ed6a6ca87af93ef1cd95610e0757641a6688517e89816a8ca39dca0910b3e9
f6f311713634ff065eb9f76d05b14d5813824fe454a352c7f5a72abe2e506169
f6f82756e8dba8b0a78bd468fc538212e3a13a95cad3c1ad2b2c203e299f7a4f
f70c6d941f1ccf42901d53cc9970f9a459a714a515a2a853d7ef43eca4d798a9
f73c1075956f2e04956b152ae11f6bf2b05002f10d2d7c315c2e0745b2438a12
f78c6ec28a3d5dbc4ad15101432c8cdb1d92bf8f6becaefb28e76267b5b8975c
f7c1686eda10dcc302f194d2767e60241f177263d0bba21b63a5ace45830fb4d
f7d546555b3af86ba83cdd75f68ede3ad8f6fc679b5df651532331f81df86047
f7f27d7e853ed010bcadd4e4cc5194bf23908c2d2fd8db869572d3becf8c41a4
f810445e85f6329531e92d1b48097a538394bb205b630999f236d8fedcdf5660
f8211b8a3b29a7f7fd318b37d040aff1df9c12307bc79fd21f7d3ba83942b7da
f84b8895e21d87207f2a3c36d7fb6dc52409cf337b78822dce8c3c3306088df6
f90fc574ebe7f1d581c1156fdeb996d0629ff95120e0cc773f805da3eb1f2364
f917264387eade253fa108085

191b7cadbd0a3f0778c50d31593c385f2a41337b2f0640c27dd426bb290a0809
194a4ac3f50f1ed7fad0ff803ec739d8c5f7bf4db981c0459f78772197f2e4d2
1a341df5fadca91a4ff6a95f21aa63cfa4346459b8e2558887a4354c23f5c162
1a4e108cf205dc077e3a84988014e32e80836781875b182327954d9fdc62635f
1ad85cbb742935eae306e07a5170a1a7ab5cd5a6f3442036675f9e1284dc41bd
1b8851158ed7212c8856270f2c4949f4963e4492a8abed205a71182061d589d1
1b938723460d405511998f366f3fbd2281dc3307ba4f81d1c34def44515bc4d4
1c25c607c77c2955c9d7da2a26a446710e20bb18ab625537d5df1cb9ce7e2cdc
1c62a767158e09a9ea4ec6f5a89fd474b4c86467fde26665c2e607a386b29513
1c9527fbc72d8b2025dbe3c2fc4d41b86431f9016df111ebd42b87a4df3f3eb3
1cbc72ac4ad478dcb4ba3aae36495485d9863886da2254fe278cd85532d0b655
1d6aac1f049a61fd8e98e2dc9951a08a06f92b51346ba4068e69315ac9412083
1d8f6bf9abc91b389e3a479c253b79b0b518935dce4cbcf49e63954d51ff6746
1de4c5d38c6c3b0cdfa8f07bf5e5c127b49aaeda25f5220802e88ed961e3c320
1f0c3583ecc813c9d7c18c7eebe3bffa1c6c65d4fd12b616a92a355701fd2d1e
1f4ca664522dbf13e7ac5ae0f

425da8f3081edda0c1720531675758387ffc344a7c04999427bef69205f037f2
435ab236eb61d92270b8c981615d42c55f36cee4db94ecaa315be2a254525ad6
437afcea225cfc118b96e299df0cc86c575c3ce0ce9b42a083a93b2592d3b630
43845d076394a5f00efafab6a7526df0b2171000ce52797e19f1c305f939024d
439c64e9cad35334632b6999e0682b627303c942d2b35c7b19b63954e7bb466f
43a0f2b8b77000cb8626624f2835104983fa019e11adafc39a4eb226f1a600ea
43d5eef10189c8bfee99c888a903af111c1a01bc350720a26ab1f7c4fa0e099e
43e3b90387b464e9140cae063643bd51d640dcef93f8025df14100aecd6a7c23
4428d1dc731bcf640b3b4ddc02d5f2637188b204ca304912388cce725521eb6a
449c1f7e09e8115e55a94b00b03006af653ef4f65827899d1f79d5c85f4cfecf
44fd32c5089af6cbfb82c653078aa1f47b02af5ee98dde0937b7a533bc003828
454a113287d59b2521a0aad7710c3b1db4a6b5072681b51a84aeb603fce21073
459adf878584e454079c35405f953e4de82f6a220d3178e0beb427a864971f66
45e54c0ee802c98897acc7f756efd56bd99d20bc1b2a09cbaa089d17a055d3c2
461ea045c61d311423da84eff396abfe2a70122c1c2a54e6940aceb64cf519f4
4639863c64ca09ef4ebd45b2c

6d7384ae7719b046f792794ee8263addaa7af4659f5cd71546eada4804669267
6d82fda76511f34e9e5205f2bf0bcd9f6aca0b2a479b9c20fa8e4d53c7fcc1b8
6dd4687b2ccb22d5ad43eada0c216fbf06e147b53ee5098468366fd477ff339e
6df7fe2223aa27c47079a0b0343d41026144d100a09f9c723bec71e8aacbd51f
6f6d727150daaeddcd0f528d52826a66106adac6e789f05db90d4137050cea6e
6f98126768c80d0e0fd7e62c4273a22f1402b6697ba8235f98e3f869be7ab4b2
6fef502572461c0a152f6de17d350b6d50d28028cdb5db4db144c2841b773637
702c04b939163d77aa36ad7249429062af62e2214ec23b60098585264a7ca0c5
704661724df95ae307f49598a5815f2750e7bd0b0bf7bae0e9becf36606f5648
70b05eec6e21b674d446abdcfb4c1af8c8f3174884557c694c70ee31e1d5c22e
71026f085b59117450cdbe7ca95a3c8f04a487f089de78a0a64cacdde8cb2108
71804035771e74ba74c403671558e48ae049f95fcd2b9632ef1d1ee5803d00f4
729ff318b24ef79bf077ed31160e4122bc41fc9edf40614c9825ed06d4055eb5
734110c155ea2c37bf747fed036e443f54ac945bda139de83265d1a9b91d17ab
73982b0c89ef6f8bc31671d308a3bd8084adc641c747a68a706c06fb83978773
75699443a1e79eaa61eab5ff1

9d83c0487d2c3823f9a2a7cd5842b940496adce08518746e0738a095e69bb387
9d84201bdbc94d3e0a4b9137b1f2d61ed15de520cdba3951f6a94d088cad86e5
9d9d6c54d6cb21452f0b16ba47256dbd15644650e42f06f3422efd44054b6333
9de866821cbb723bc495b1cb6a84c01084130f993c28f071f8775ccd6adc0f9f
9e276cbada5c885d548aebe517a4cb11ef7a549bc4ca0e5e98eaad3e64574b99
9ec26211a7b920c2ccc0c5e2593fe3f8693f24be2c2c0a919b5cab9565857faa
9edf95266c1357c1e50b78660180b7cb4cc356821f5e1497017c943ee9c80066
9f1344b0f291f1ab5609ff4afa668e20292d80bdb2d49645e4c7b7eb3ad0f6ea
9f98817c996a401296e4ac1b56e6c170b5598836631df9be07159a8882925756
9fa72cac945bdf10493e19d3ae6e2e16cc532fad2421926754a0e37aeff7843c
9fec635d9ffb9b86d9e07a66eee6d7f8a777b3f891b6d6b40882dd739eaf4b29
9feeba9eabee6f8e603c6da33fef46333c9223c37ec9679ef9cdef740f51dab1
9ff934cbd1d8cb2013722b549057450b45974e80f9c1ba60eadbfff16b77b5b6
a004f9ca670fca2c019aeef1f873cbb7a4d59ecc4637061dabd803840c6d094d
a010918f2bc4eb01b23903b576ecef44f4d922f40a8876503dafd45a2cc57b7b
a04e0da90281b6b3a1c72aabb

d42e46aef26496fd8cbaefabb3d7dcf966047caee3175fbbb8bfacf99fac708f
d47f7d8bda264ebc70cad41df27b87c9ae96f9c7c79509444bbeddd61f7678db
d4b8b2ebf6a79973bbc0b0928bef47fa420f8f9bcc0536a9f0a7d525496066e1
d4e44e293bf242ee66af0973f6ca5c39766431131e41d7acacb2694312f0547b
d5472acb4ebfb814368cc2c5c47c14414d85374fe4ae5cb274db635a29198d0f
d5cce8a7e2ff368cf16a3afd3e81e5d66982a85321aa1b0654e7e671c07356be
d5ce7e75c9a680b65e0da2aaeaa4fecd569c4a8491a7f9c4453c872fb9cd1e9c
d602b1142de3d9faaeabcbedeadf393aa223d2e9f784418a2b022fec059d5742
d66f360874663d905d25f44b6b046b550029f7bd4cca473838d9385b4d473709
d6d68d590f739a54837ff28637a19dfde1ae41607ccd52444c06612a90aa945c
d6ec73a09cea411ac9e5090e42f0f4d198c2dcde4e508c0a9ec54c821c20a190
d7170e3a52dc5f5d01e1d5d79e7d3627b6fc8ce9764d1092640d475d58303adb
d794e3b5c3db9bd9d4d9ed8c280abc823d6da23a3efcd65530b675ca1b4138e9
d851740f46f4f672b1ef6151c1d0d03aac7c35ab3dc029f2c00c1e69629e47e8
d8b270ab13e9938304b6df12c5887c1d4cba57c1c443275df7f9764213e02e3e
da361f9b07f412e239d0be4a3

0118e971ce5e96a2563849fead200a12d01d953c53e68889a430e67f59bd9e14
018bbe9b20172fa4852bd4c0b5b33341a9d762759d9dcbccfe403b2921e8f003
01a5c59be6a604638a6a4d26a0378f244455fb6d037138e9e036cad21f343aa1
01d3ef697bb85210e9e7bc6f024e04fb1ae94401ddb8566a94d40a62f6b3593f
0263bfe4004755185ded376e186511eedd9f5a190144ac6699fda9cb038ad178
02747f291316568db1fac646cbe842f4663f7c3abff2894a835c69b330e81be2
02a886930bb7b19bdc31aba13b37903462495768c5d217358c075719b609e170
02ff904e5de06ce8fb85f7b4c64673d136426a6b6e89fa34c16ed144b9202445
0304379f16b6be2e06e2653fb0b327faaac7ff1cc5e0df3ca36c8adb2b41232d
039681805b3ab054eb3ff6e84f19f872d5e2164ba82a3db92678406ef67b97e0
039ea2546749dd661f0c48f821374d74282e13114310902e1e74f14babf61990
0434d964baad8bd7d8220fbbac53df31bf8c447283b9f962961bf79b6949efa8
043d175afac5e3f54cfad2a85667cd487736101bc43e7ad6a60a97f8c5721013
0464609ae775a46cd4a90fb1b7ff02a0643ecbfcf4f666f57ed428744dc470a9
046b7512d071ac3a3c3787c1cf24254fbc42c6fe60097405d71bb15fa3ed4c4a
046bb2a96b1a5597d24e6ac8a

248947b027d763fefabee1c2d744483503d17881f346c76e213ae4a731c26dba
24a407b5d3cfbb94f9c1d003d0248ed2de8f22f22a52b2d04a4479b6bceef994
24b030e4560f99ba0285051d55503c1039162e6214705539741d1b5966e5008b
24f789aac0bbb94519a4d6a57955321c62016efc8f5378b9820bb3caf9cf8684
25186f14d70eb7ea492b24c9b165c3a328dcf4455905a508e2836da0e59bdf36
251dc0db10f7472c742db036256f52e42359492b6bf9c23bdbf3cc4baec0f0eb
2589d8724446e59e597959a9dfb62d1d1eee7010a552970eb63b6a89922d1147
258e4748e6629f4542f0687daab775719697ffbda2af56663be3d06c443a23a5
259c97bde696a77385222273c9102c447577110821912598777712114ac61148
259ec0082d72baf324c68dffd3199423d0da2e9fdbecef77373b4f7ff04d77ea
25d2ff0daaa477241621cafcfcefe7a91a822de22b533e8794d1312af076d3e2
25f89544ae762a795fe97f7625e9bc55a8ebdaaf8856fc6b184fa92eaa35898c
2644bc959eff34bc90a21bbb86477e0db05f778950e3a70444c5f4ed90e8beb4
266e582fa3f8f0229343d6dbb892d95416059edacb65d0dd10a38c732e9ecc0d
2676a2d65f56eabc9d45a76f1700e80398005ba6ea71e48d404bc2a68a70bcbf
2722f6f583ee8579e87cfb9ee

45b6c8ab5f35638582c3f3397b683d8d16e575e0ceb65ae507eed597fb24be8d
45e4bd373c277b5aa87167a3d670e9f173f64d6b133ea7ac4108c1972e663c76
45e66124413e460bb587600aaac42077c8258d70764491e3d703cb7f855c4c43
46049243e207c1f08c64bcea1329ee3433d85cdaae81ed0504fd31ce497058d8
4613caa1de1f4d20759e249058f532547d8a1357e1823b1b3bb0bd09d46b8f7c
465cce528b5c6dddd955703b8a250ec478865d6b149264bc586615a34c962451
465dc646e00200519978125ee9fb0eeb275ad1f9a1c318f1d51c90cda802725b
46750af5d17d509d6e2abec3e3fe4766500c867d9e2cd47a386568fa71b2577e
473868b96a069c69a1346665b5c8bcb63b2fffd2800d6bd0d14c9a0956af3b37
4767e7aeb841c95dfec50aaed6975c517867e5dfa9e282c2d56c878437886f04
4778a677151f90026e4dcb4f8e0495ea3a9eefc315b79a5fa85c97e7d23e8836
47da8a2d789022713db09787b71c5a6b58d85ae60e4bdaece3222ea12e6b6e82
47f92ccb451749d4e302f83885dee8d1617fe3adc2972329933a0ecb2d42c4a4
48051cf392f14fd97c2875db88d6f3c866bec668bac71be1d166894f26ad9794
480cb17d8456511c1e448dd6f5d626dddfd74c35ae507d2750781500c41dbb88
48169446b66a00b88a1952783

668677941382e9e29d4dceef21aa7a7d3ce3a4a99df443c3df48db3b691f45ab
66b17293a799b964b1baae41357ef245a1e1cac51c831beec3f1976a622483fa
6737b0d2cd96dd69e43b25f5ccefcc250994241588224b87da14d673e87a897b
67403ffd3b4804e129e6ecd378ffcae1da3aa608c55eb4893a2f619d784f9b45
678290606cc00e5bf0e174489a4bf136d6e667e983b268155e2b2da47f841f94
67b1adca495272ec335154b37d136ea641b7f8af23b3142e06cfde8675fa1bd8
687eaa03245c614b98480a1d6b35dffd4b7779fd89c9af3e31dd35a13f568b9f
68f354d33f6e8470305b69e83304d0ad86d28077b7924ccd7cf04671c7551fcf
68f43e31103f9f7ee137436421ff616969ea76f11dc3f590d44a6b4699170d0d
69040c2ac7cd73cf6e57c8650a9b4aac0b3c086708b107a713d95a6d9affaa93
692b5ae63fdd7f669adcf147c78cefed2df364ef4d3e9713ee23cf76f38ec8c3
699364bc53839b3d3bcc760c4df8e42aa39b190f774a36ad4567c5fb5d8fc9e3
69a34cc3495ca5174f8e48a07477035b3bf0cf464857871e35b8c7b139089799
69c3ed6328c4dd247695a3a306736f99fcd44522a20325519388c826955f1c4b
69dde2d177eed2115897d01e4fb816c006d59e0b0867c4d4ff14818a493f3d95
69f347c8a3df85e690eeafe87

8894a781dbb36acf6044ad22adf47391ca68fc8269bb5d42702fab58eedcf7ad
88bd7f92380d2156388541877127897e3ba514d6a47aa87b9244aeb763dd6539
898da2f38a3585cb461454a2700ede6747ab2c3615090184f90750b09b62fb03
89d34733f29bc1149d9efc7b2ac65a2ba33b97eba2815297dd95978ef4bbf49b
8a5668da083dc71b2602f71f539718014022381bc228c9885971f1a35b7de095
8a7f82fd5fbd63379c9c3a68cde83d7163b4b90a5ca301039dafa76dae793da5
8a8ff56ad8b45bebfaff50ee3452e711c75cbd83f327804c47b6e8dc67fb29f1
8ae468f591f66dcd553ffb1c9d29ef00c37ee3f479de466a94db5860a80f66ea
8b60a17956fb4960f4d49eafbe8cc982ec0f1bdca0d806b8760dfea6b1d8306b
8c025f3f7b08c109939b577ed0926dedb5266fed9f4b269a3f1e831af71ff039
8ca713e52d8bdf2fd6431f87d30a6d4aadfb87c5afd8e1ea00107504a87b6b2e
8cd060e95c51c0a9b78b32ddcb65a471b040ecb806c8bd2a412eb5e1c9df72dc
8ce5b08bd6b43ea84a72435ee46b0bfee07b272c0c41e0b4a3b3a48940e58691
8d3b4353ac231ed05ba20fe47b8c150d3074c8b027b5f307e5a1134ac630ec49
8d93351e9161bf70fa1043607bab99ca26ae71b2aa0465fb5ef42f3ad75ae44d
8dac578a6d6601ca761a6a20b

a794eb528a20054b86e7948a086ddb83c37d32748b516358c0660a239cbae756
a908ad6885c9a64a18f6534194e5f8ec134beb9a1f2e39de8bc15e7ada09fd09
a9ad0f8b42da9ffa96b7a721de3b6defbeb0fcf14802a0a3859cec34f61ae0c7
a9ecfb5a44248a2016a1a595333a1f9370b33a8a581885a1bd15cbe216d071f0
a9ee6cab2dc7968d325728bced1ec07998816f9a9400e212f6c9962913cdfc3a
aa4fb4c668657ba3f057726ddcc900b6c52173fddb6c2008b9b46e0ff3585c5c
aa670389164a259e5d4a001fd45bcfcd020d3a2daef17ad4c0429e2f53b7ef85
aabef7b1deb0bb587952ca25c5dc9d0ea265a312ff204073c005cce933168a02
aaf8eeb21eab071c32f24455e0b23872738cc54e8ed4995f7bfca12d53333b86
ab47ac5fd793a5552c3f70d469a010684ae00f238459dedb9292a789bdf1b8f9
ab8271b0f9e25b96d95e7fd6d47364354d121aae02c07419de80e44471ce07fe
ac86be5572efa076572930171e26ce39bfbfc79ab6e482f9ced2ae6fb27dec3d
ad2e62229d60e408b4c1c98a43a432c4cb1dbbda52850ab5ab13f0b3cb831082
ad33c4ebc3de4d23fb1cf5b3bdd124c2f762e765f8b39605a019e3465298bcf7
ada8445cfccd0064ba1022ebe2e5b90c66a734e562b18e4195cb0ef137d615c1
ada8787aad79e1a5df8977fc0

c7b811cbed4afc45d1d64a5451b792b5022f042567bc295563cfb82082d9e007
c7ca470c8b9d8af6e8b32e8addf44bb33f901c6540eff63b9384daf245a7ecbf
c8023f50f069363ae1d20ae88cb2b4b7398c75dce5641db297d7979e6311ad4b
c8157b448f124faab416aa20923022282f78aa85afebb37cd7175427782e8e11
c84e28f9e5153785d63e0946745a965b430e7ce706d88cc26454f030d0e52e4f
c84eab98855a5d3555a495758581eb2cc693da74db020719d91c5b0f6413ded6
c99b186340ee30deb64057416ba71a9d600147fbd946b89356ee04b1b32cee98
c9a0113932d31737baa8868449e4196ebcef84560023893267003d0d3a7c3a1a
ca17b7beff3b760ca3707cd7e52db3f5ca281cfe5bd84ce9af05784946e3e659
cabaf7586e9de0a352b6588ca6109106fa5750dfdf330c198ce014f5f1603229
cabf7e10a15f88f55ef79ccaef29778b3655cf596cbdd0bbbf55a47fdc86af19
cac9472e42b29ef7d609b1cc089beebbcb732d4fd7c4bc8d2ebc92d567c78b7b
cafe0c48699ae409a5ab71d2d0ba1059da4e8d75fb78fd227fa6b565f2ee635a
cbea84b699c99e7bb76320adaabf21cb723068407de18956538ada1d8165444d
cbecdc67e6bdafc65948950d2debab6122744149571b038f99791083f78fb7ac
cc35f7b440a0755fdbba81b19

ecf178a7cbf0846defabd13a07b0f743069ec0ed30073822c64508a75305e1f6
ecff8bc224b1b42c4d2d8b20e8f342608d174f35ef7b984de3450534f43f23ba
ed16e0ca2df031154346238b69773b13e3a25ecc6789f69849c9806bfb84f413
ed1baa8624d6d4e0e2d573b3d42501651cc411a068d764fcad679a2c99612cab
ed941e33cd45b94d17c3fa5ab42ce9dd0781c7c02746aaf2fc1f4438b890cea5
ee29e3e2a0836458719b116ddf134bcf33f617c82b97c78719569c0c3f81acae
ee660cb7224fc636e8912ce5450367f9213393773be8c0308a1ff1d7a30892aa
ee6ac743ba4d67a824d299cdcd7e51bde75185ff4e67f3e9a820017249f09091
ee9263409dad15d2b82ba9c65c07eb543c1939aeee53a44fcde8809040299621
eeb334d9e463fa7ade7dbf5be330ad574b8eff589b70278e6902c6cbcee16baa
eed1df6dd50dd06f8334177f5cb3ce50ac37396dbf3c184bab83929ee0ed8bb4
eede0455f9b5cc7a3b2df49410f7fcfd0e27a0fa6af1cb6efe41b846249807c4
ef1946ad68f377f8ada288cd53aeb09f98548dbc670bba8f2ff6872331da34bb
ef2dadb46c5f6a172005ea5b6857279dba7be3eabc920a206d9ca33fb07eaa7f
ef968b2ba418e0b68ef6d9fe2dba03866f7ebf4b058dc4af468c9239c390356c
efba03a6351e4cd32ce24bdbf

0be644181ec2502de46d2d30a0a17daefae22b8ed418da1937d937f1266daefa
0c8eb152518f2ef165f71e25f8a64a0520cda84aebad2abbd5cad6ae1b03b800
0d4b309a32f4d5b3221dc66cf81b6103deef76a80be9096c7dac48242cd54971
0d7a38e8e41691f15d4135342efa73457b50a52043de853d4eb437765b285a17
0dc193de929fbd88d67b4f3c4a8f56b47a06c1ccf8c133e3a64b1c50359acd81
0de54ec1e8a0f20c63a97c9adf1dbcc82b6ca1d7376ea3499985e3d8dc549eb5
0eaf33b01f0bd3e50a2227ac13cb6df3dda271b6e59f127d7696089d2c58506b
0f8dd64476c5d7de6e5fb8a4ed9a484add9fda14492428d171251aae75b92780
0f9967004fe56b55ea0db8429e124d7bd763c882b6dcca6a2e72fcb4de41fb65
0fd882a895a738df4c0e10caeab812134a262401645a36abe2301b18bacf8350
0fea7acb6e8b7049d477025a396beb487ffea509ddc9ea2732911a08b3f721c4
10aa569a277985d02b62b1176deb680e3162909614bcfad060b8351a34419df7
10ccba7285244c9bbfef2c74d4634fdf9f70114091f772cbea4346b2378b5474
10e0e2d3b84e322cce7c53efd1a00abc8c49b233857c4a19ebd885f9cab9f3d6
1110ce5b4dc6836f520c7d75e8e458959a6536c560ab6f31e4e648b1daa40a15
112da9ffbc36ba83d60ea467a

37b819e8a7697d4714e9b1de9242e7b81d9288437a3c62c6f4b966c3f676a167
3859c7115701d968be49f4a4b1895607a8e4f15857d72c1a8e49da0a2a363c5c
388ca07c4496c2236561722c40c0b8d2bc31fbcdbffdbccb6aea0b5ade64a561
3894c1fc685457cb0fdc865510bf8317ae5651844535de59902c7c006b1a8ba6
38adb155408d333fef2809c821effcd0c47919b81ef0eab144e082bc06d8f834
38ce44dc98187e745c5ede63163e37db232c8c3c47ad6836f96fc0a6aee7893c
397b47e79d9a5429caf93d122c58f7a6aab3f89494ed04059a8fe1344bf80b6e
3ab61c27d7556bf36b023049e4bd1d8996964c92d2586c17bc32db9dcbd56d63
3b42838bff1898ad41566265b1c8f6aa3640617d726b307e2030e636f219f468
3bcab54ca90cc4c6b8fc46ee961f9f015d6a16250f8cd42c6bc8b6e1c21ee81b
3c1291f112afde1b13cee90b33f43cac2f1e9d23a0f9b9a7ad113a4f97058ee9
3cb6991699d539268edc6e94e0d5a54150fe62a8c51c5e94d2198dea35a509ba
3cd2d659125f30821d6c4b5a6ffcb6ea33127f32a477c9397f9dce08cadb1575
3d0b2ba032fcfad20a7cde3d183b821e2c5d4b3385ff80a3f80748b4b6428e58
3d0c7f09b7cc6986785fc98a6d1676b4a9769a085f649f3c15a0c3799fcde124
3d33f7bb7bd4dd4359dcc3f41

754acfa2e59051b105065ca60264976932bf40b19a45b35091a17b43b90782fe
75670a9bd4b2be9835b0caf086b0836358712dc468a0fa049e6217d43db5a87f
75892fd7b0f095656d42ce1cad253a754faf61d52982c4ce36c9b345eeae3ca5
758dda10c0e15be97d8046225cd12823cf8fc9f5dbfa01bdeb40ee0099269560
75986afcfa08019e413811b9441267b29703795d9f3d2d66163a51baf0774be0
75b3abe60c602826d1011ba9734ac96be9b9202262d59d75d620e5e471fe7736
7670eb5968995451ee81831f62b40ef484ce8ce3a864dcbe4471b40573af379e
7762a889fbf20797dacba8afdd3392467ef24c52af7e231731f6e71043acbaf1
783155c36450020fe175b6b21e3292669b4687390864c3cbe62a2e8f755eafd1
786789b047d78c89619410d357edc841c2abf06c52d3a5d83b3a966ff38e1a5a
7883c06d056a19659b97ab8452773696bd0d6d6368c0e31d20ac59ce66c60f72
78cb3a281b8634042b14accd9eba5a1fa747d96339bbfef76acf49abcd91ad4b
79c568bf65a32d438cd4d32e77b5ce3ea7e4e079f4c4adca21de798ebfd2d841
79c569cb3268955254abbfd760a6d299203cc9acf35030c40da8db26aa6a42fe
79e5ef2a811f90eabaa9d0a5c8208f685773b46f7c208de4cc927231d133bf1d
7a1cab6dddfbbbd3822143182

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [13]:
print(similarity.shape)
similarity

(2580, 2580)


array([[1.        , 0.08752494, 0.03553044, ..., 0.0414969 , 0.05856691,
        0.05257793],
       [0.08752494, 1.        , 0.10135107, ..., 0.31094455, 0.06615457,
        0.11935168],
       [0.03553044, 0.10135107, 1.        , ..., 0.07494133, 0.08330942,
        0.05427305],
       ...,
       [0.0414969 , 0.31094455, 0.07494133, ..., 1.        , 0.03937336,
        0.09324698],
       [0.05856691, 0.06615457, 0.08330942, ..., 0.03937336, 1.        ,
        0.58740676],
       [0.05257793, 0.11935168, 0.05427305, ..., 0.09324698, 0.58740676,
        1.        ]])

In [14]:
print(len(Customer_IDs))
Customer_IDs

5993


array(['00357b192b81fc83261a45be87f5f3d59112db7d117513c1e908e6a7021edc35',
       '0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56ee9b59e6619d899e332',
       '00be0a263381af38132d31225e8fb12fbc527c654b446484fb672a78118f037d',
       ...,
       'ff666e1a64239927cc36e9b3f474ad6e613ff63742cb15c717ae51cc5e4c7ffd',
       'ffc21861854c3e3cf2dbef233cff8ba29a1dca5ff384651e9463a89674a2641c',
       'ffd70e82342cd4417db5458ae282c1450587734a9e00f81274afed82144f5540'],
      dtype=object)

In [166]:
# in a for loop
## for customer in Customer_IDs
customer = Customer_IDs[2]
customer

'00be0a263381af38132d31225e8fb12fbc527c654b446484fb672a78118f037d'

In [167]:
purchased = list(X_train.loc[X_train.customer_id == customer].article_id)
purchased

[589549018, 685604015, 732675001, 669385001]

In [168]:
#empty list to store similarity array for each purchased item
similarity_items = []

#for each article_id, find its 12 most similar items' similarites
for each in purchased:
    #article_id's index
    item_index = np.where(article_desc_df.article_id == each)[0][0]
    #use article_id's index to get its similarity vectors with others and append to list
    similarity_items.append(similarity[item_index])

similarity_items

[array([0.04261463, 0.20167606, 0.03974173, ..., 0.07246312, 0.0700987 ,
        0.11319982]),
 array([0.06674879, 0.03671266, 0.02434916, ..., 0.01362617, 0.2126426 ,
        0.09999439]),
 array([0.04233117, 0.20816835, 0.03580461, ..., 0.08029607, 0.03529698,
        0.0761465 ]),
 array([0.03460086, 0.18215487, 0.06643741, ..., 0.11445889, 0.090424  ,
        0.15733394])]

In [169]:
#convert sim_temp_list to np array
similarity_items = np.asarray(similarity_items)
similarity_items

array([[0.04261463, 0.20167606, 0.03974173, ..., 0.07246312, 0.0700987 ,
        0.11319982],
       [0.06674879, 0.03671266, 0.02434916, ..., 0.01362617, 0.2126426 ,
        0.09999439],
       [0.04233117, 0.20816835, 0.03580461, ..., 0.08029607, 0.03529698,
        0.0761465 ],
       [0.03460086, 0.18215487, 0.06643741, ..., 0.11445889, 0.090424  ,
        0.15733394]])

In [170]:
#replace 1. with 0 in the similarity_items (1 is the item itself)
similarity_items[similarity_items > 0.999] = 0
similarity_items

array([[0.04261463, 0.20167606, 0.03974173, ..., 0.07246312, 0.0700987 ,
        0.11319982],
       [0.06674879, 0.03671266, 0.02434916, ..., 0.01362617, 0.2126426 ,
        0.09999439],
       [0.04233117, 0.20816835, 0.03580461, ..., 0.08029607, 0.03529698,
        0.0761465 ],
       [0.03460086, 0.18215487, 0.06643741, ..., 0.11445889, 0.090424  ,
        0.15733394]])

In [171]:
#Get index of 12 highest similarity for each purchased item
high_sim_index = np.argpartition(similarity_items, -12)[:,-12:].flatten()

In [172]:
#Get similarity using above index info
high_similarity = np.take(similarity_items, high_sim_index).flatten()

In [173]:
#make a dataframe
item_index_sim_df = pd.DataFrame({"item_idx":high_sim_index, "similarity":high_similarity})
#sort by similarity and get the first 12 items
item_index_sim_df = item_index_sim_df.sort_values('similarity', ascending=False).reset_index(drop=True)[0:12]
item_index_sim_df

item_idx  similarity
0       2012    0.975422
1       1421    0.949447
2       2268    0.947333
3        633    0.947333
4        634    0.915488
5        456    0.884409
6        264    0.825460
7       2464    0.806010
8       1967    0.798584
9        351    0.792591
10      1963    0.787938
11      1207    0.765960

In [185]:
list(item_index_sim_df.item_idx)

[2012, 1421, 2268, 633, 634, 456, 264, 2464, 1967, 351, 1963, 1207]

In [188]:
#retrieve the article_id by index
recommend_article_ids = list(article_desc_df.article_id[list(item_index_sim_df.item_idx)])
recommend_article_ids

[589549007,
 589549015,
 589549020,
 589549011,
 397688006,
 585355004,
 585355001,
 721063001,
 721063004,
 730013002,
 721063005,
 589556001]

In [125]:
np.argpartition(similarity_items, -12)[:,-12:]

array([[1207, 1963,  351, 1967, 2464, 2268, 2012,  634, 1421,  456,  264,
         633],
       [  86, 2060,  714,  310,  771,  326,  232, 1605,  905, 2290,  160,
        2568],
       [ 524, 1731, 1040, 1972,  806, 1282, 1429, 1094, 1677, 1430,  588,
        2315],
       [1448,  141, 1359,  842, 2249,  569, 1515,  941,   90, 2443, 2435,
        2266]], dtype=int64)

In [128]:
np.argpartition(similarity_items, -2)[:,-2:]

array([[1421, 2012],
       [ 160, 2568],
       [ 588, 2315],
       [ 569, 1515]], dtype=int64)

In [130]:
np.argpartition(similarity_items, -2)[:,-2:].flatten()

array([1421, 2012,  160, 2568,  588, 2315,  569, 1515], dtype=int64)

In [129]:
idx = np.argpartition(similarity_items, -2)[:,-2:]
np.take(similarity_items, idx)

array([[0.94944714, 0.97542231],
       [0.15764962, 0.1389232 ],
       [0.06126165, 0.17320611],
       [0.32754533, 0.06931327]])

In [131]:
np.take(similarity_items, idx).flatten()

array([0.94944714, 0.97542231, 0.15764962, 0.1389232 , 0.06126165,
       0.17320611, 0.32754533, 0.06931327])

In [132]:
dff = pd.DataFrame({'similarity':np.take(similarity_items, idx).flatten()},
                   index = np.argpartition(similarity_items, -2)[:,-2:].flatten())
dff

similarity
1421    0.949447
2012    0.975422
160     0.157650
2568    0.138923
588     0.061262
2315    0.173206
569     0.327545
1515    0.069313

In [135]:
dff.sort_values('similarity', ascending=False)

similarity
2012    0.975422
1421    0.949447
569     0.327545
2315    0.173206
160     0.157650
2568    0.138923
1515    0.069313
588     0.061262

In [ ]:


#concatenate all text information
X_train['details_description'] = X_train['product_type_name'] + " " + \
                                 X_train['product_group_name'] + " " + \
                                 X_train['graphical_appearance_name'] + " " + \
                                 X_train['colour_group_name'] + " " + \
                                 X_train['perceived_colour_value_name'] + " " + \
                                 X_train['perceived_colour_master_name'] + " " + \
                                 X_train['department_name'] + " " + \
                                 X_train['section_name'] + " " + \
                                 X_train['garment_group_name'] + " " + \
                                 X_train['detail_desc']

#subset article_id and description column
article_desc_df = X_train[['article_id','details_description']].drop_duplicates().dropna().reset_index(drop=True)

#TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(article_desc_df['details_description'])

#Calculate cosine similarity between articles
similarity = cosine_similarity(X)

#sort index of similarity
sorted_sim_index = np.fliplr(np.argsort(similarity))

#find customers in training and their purchases items
Customer_IDs = X_train.customer_id.unique()

#dict to store each 
recommend_items = {}

for customer in Customer_IDs:
    #find purchased article_id
    purchased = X_train.loc[X_train.customer_id == customer].article_id
    
    #empty list to store similarity array for each purchased item
    sim_temp_list = []
    
    #for each article_id, find its 12 most similar items' similarites
    for each in purchased:
        #article_id's index
        item_index = np.where(article_desc_df.article_id == each)[0][0]
        #use article_id's index to get its similarity vectors with others and append to list
        sim_temp_list.append(similarity[item_index])
    
    
        